using System;
using ProtoBuf;

namespace KKSG
{

	[ProtoContract(Name = "AuctionSortType")]
	public enum AuctionSortType
	{

		[ProtoEnum(Name = "AUCTIONSORT_QUALITY_LESS", Value = 1)]
		AUCTIONSORT_QUALITY_LESS = 1,

		[ProtoEnum(Name = "AUCTIONSORT_QUALITY_GREATER", Value = 2)]
		AUCTIONSORT_QUALITY_GREATER,

		[ProtoEnum(Name = "AUCTIONSORT_LEVLE_LESS", Value = 3)]
		AUCTIONSORT_LEVLE_LESS,

		[ProtoEnum(Name = "AUCTIONSORT_LEVEL_GREATER", Value = 4)]
		AUCTIONSORT_LEVEL_GREATER,

		[ProtoEnum(Name = "AUCTIONSORT_LEFTTIME_LESS", Value = 5)]
		AUCTIONSORT_LEFTTIME_LESS,

		[ProtoEnum(Name = "AUCTIONSORT_LEFTTIME_GREATER", Value = 6)]
		AUCTIONSORT_LEFTTIME_GREATER,

		[ProtoEnum(Name = "AUCTIONSORT_BUYNOW_LESS", Value = 7)]
		AUCTIONSORT_BUYNOW_LESS,

		[ProtoEnum(Name = "AUCTIONSORT_BUYNOW_GREATER", Value = 8)]
		AUCTIONSORT_BUYNOW_GREATER,

		[ProtoEnum(Name = "AUCTIONSORT_BIDDING_LESS", Value = 9)]
		AUCTIONSORT_BIDDING_LESS,

		[ProtoEnum(Name = "AUCITONSORT_BIDDING_GREATER", Value = 10)]
		AUCITONSORT_BIDDING_GREATER,

		[ProtoEnum(Name = "AUCTIONSORT_PERPRICE_LESS", Value = 11)]
		AUCTIONSORT_PERPRICE_LESS,

		[ProtoEnum(Name = "AUCTIONSORT_PERPRICE_GREATER", Value = 12)]
		AUCTIONSORT_PERPRICE_GREATER
	}
}
