using System;
using ProtoBuf;

namespace KKSG
{

	[ProtoContract(Name = "ErrorCode")]
	public enum ErrorCode
	{

		[ProtoEnum(Name = "ERR_SUCCESS", Value = 0)]
		ERR_SUCCESS,

		[ProtoEnum(Name = "ERR_UNKNOWN", Value = 1)]
		ERR_UNKNOWN,

		[ProtoEnum(Name = "ERR_PASSWORD_ERROR", Value = 2)]
		ERR_PASSWORD_ERROR,

		[ProtoEnum(Name = "ERR_RELOGIN", Value = 3)]
		ERR_RELOGIN,

		[ProtoEnum(Name = "ERR_ACCOUNT_NOT_EXIST", Value = 4)]
		ERR_ACCOUNT_NOT_EXIST,

		[ProtoEnum(Name = "ERR_NAME_EXIST", Value = 5)]
		ERR_NAME_EXIST,

		[ProtoEnum(Name = "ERR_INVALID_NAME", Value = 6)]
		ERR_INVALID_NAME,

		[ProtoEnum(Name = "ERR_STATE_ERROR", Value = 7)]
		ERR_STATE_ERROR,

		[ProtoEnum(Name = "ERR_PROFESSION_TYPE", Value = 8)]
		ERR_PROFESSION_TYPE,

		[ProtoEnum(Name = "ERR_FAILED", Value = 9)]
		ERR_FAILED,

		[ProtoEnum(Name = "ERR_ACCOUNT_ROLE_FULL", Value = 10)]
		ERR_ACCOUNT_ROLE_FULL,

		[ProtoEnum(Name = "ERR_ACCOUNT_DATA_ERROR", Value = 11)]
		ERR_ACCOUNT_DATA_ERROR,

		[ProtoEnum(Name = "ERR_TIMEOUT", Value = 12)]
		ERR_TIMEOUT,

		[ProtoEnum(Name = "ERR_SKILL_CONFIGERROR", Value = 13)]
		ERR_SKILL_CONFIGERROR,

		[ProtoEnum(Name = "ERR_SKILL_LEVELREQ", Value = 14)]
		ERR_SKILL_LEVELREQ,

		[ProtoEnum(Name = "ERR_SKILL_ITEMREQ", Value = 15)]
		ERR_SKILL_ITEMREQ,

		[ProtoEnum(Name = "ERR_ACHIVE_NOTCOMPLETE", Value = 16)]
		ERR_ACHIVE_NOTCOMPLETE,

		[ProtoEnum(Name = "ERR_ACHIVE_NOTCONFIG", Value = 17)]
		ERR_ACHIVE_NOTCONFIG,

		[ProtoEnum(Name = "ERR_SKILL_POINT", Value = 18)]
		ERR_SKILL_POINT,

		[ProtoEnum(Name = "ERR_PROF_ERROR", Value = 19)]
		ERR_PROF_ERROR,

		[ProtoEnum(Name = "ERR_PROF_LEVELREQ", Value = 20)]
		ERR_PROF_LEVELREQ,

		[ProtoEnum(Name = "ERR_PROF_LEVELREQ2", Value = 21)]
		ERR_PROF_LEVELREQ2,

		[ProtoEnum(Name = "ERR_BIND_SKILL_OUTRANGE", Value = 22)]
		ERR_BIND_SKILL_OUTRANGE,

		[ProtoEnum(Name = "ERR_BIND_SKILL_NOT_LEARN", Value = 23)]
		ERR_BIND_SKILL_NOT_LEARN,

		[ProtoEnum(Name = "ERR_BIND_SKILL_MISSSLOT", Value = 24)]
		ERR_BIND_SKILL_MISSSLOT,

		[ProtoEnum(Name = "ERR_ENHANCE_ERROR", Value = 25)]
		ERR_ENHANCE_ERROR,

		[ProtoEnum(Name = "ERR_ENHANCE_LACKITEM", Value = 26)]
		ERR_ENHANCE_LACKITEM,

		[ProtoEnum(Name = "ERR_ENHANCE_FAILED", Value = 27)]
		ERR_ENHANCE_FAILED,

		[ProtoEnum(Name = "ERR_ENHANCE_SUCCEED", Value = 28)]
		ERR_ENHANCE_SUCCEED,

		[ProtoEnum(Name = "ERR_ENHANCE_MAX", Value = 29)]
		ERR_ENHANCE_MAX,

		[ProtoEnum(Name = "ERR_ARENA_ERROR", Value = 30)]
		ERR_ARENA_ERROR,

		[ProtoEnum(Name = "ERR_ARENA_COUNTLIMIT", Value = 31)]
		ERR_ARENA_COUNTLIMIT,

		[ProtoEnum(Name = "ERR_DECOMPOSE_FAILED", Value = 32)]
		ERR_DECOMPOSE_FAILED,

		[ProtoEnum(Name = "ERR_DECOMPOSE_CANNOT", Value = 33)]
		ERR_DECOMPOSE_CANNOT,

		[ProtoEnum(Name = "ERR_DECOMPOSE_NOTFIND", Value = 34)]
		ERR_DECOMPOSE_NOTFIND,

		[ProtoEnum(Name = "ERR_SCENE_LEVELREQ", Value = 35)]
		ERR_SCENE_LEVELREQ,

		[ProtoEnum(Name = "ERR_SCENE_NOFATIGUE", Value = 36)]
		ERR_SCENE_NOFATIGUE,

		[ProtoEnum(Name = "ERR_SCENE_TODYCOUNTLIMIT", Value = 37)]
		ERR_SCENE_TODYCOUNTLIMIT,

		[ProtoEnum(Name = "ERR_SCENE_NEEDPREVCOMPLETE", Value = 38)]
		ERR_SCENE_NEEDPREVCOMPLETE,

		[ProtoEnum(Name = "ERR_ITEM_NOTEXIST", Value = 39)]
		ERR_ITEM_NOTEXIST,

		[ProtoEnum(Name = "ERR_ITEM_LEVELLIMIT", Value = 40)]
		ERR_ITEM_LEVELLIMIT,

		[ProtoEnum(Name = "ERR_ITEM_CANNOTBEEQUIPED", Value = 41)]
		ERR_ITEM_CANNOTBEEQUIPED,

		[ProtoEnum(Name = "ERR_EMBLEM_NOEMPTYSLOT", Value = 42)]
		ERR_EMBLEM_NOEMPTYSLOT,

		[ProtoEnum(Name = "ERR_ITEM_NOT_ENOUGH", Value = 43)]
		ERR_ITEM_NOT_ENOUGH,

		[ProtoEnum(Name = "ERR_EMBLEM_MAXLEVEL", Value = 44)]
		ERR_EMBLEM_MAXLEVEL,

		[ProtoEnum(Name = "ERR_JADE_MAXLEVEL", Value = 45)]
		ERR_JADE_MAXLEVEL,

		[ProtoEnum(Name = "ERR_JADECOMPOSE_NOTFIND", Value = 46)]
		ERR_JADECOMPOSE_NOTFIND,

		[ProtoEnum(Name = "ERR_JADEATTACH_NOEMPTYSLOT", Value = 47)]
		ERR_JADEATTACH_NOEMPTYSLOT,

		[ProtoEnum(Name = "ERR_JADE_COUNTNOTENOUGH", Value = 48)]
		ERR_JADE_COUNTNOTENOUGH,

		[ProtoEnum(Name = "ERR_CHECKIN_FULL", Value = 49)]
		ERR_CHECKIN_FULL,

		[ProtoEnum(Name = "ERR_CHECKIN_LACKDRAGONCOIN", Value = 50)]
		ERR_CHECKIN_LACKDRAGONCOIN,

		[ProtoEnum(Name = "ERR_ACTIVITY_NOCHESTINDEX", Value = 51)]
		ERR_ACTIVITY_NOCHESTINDEX,

		[ProtoEnum(Name = "ERR_ACTIVITY_HASGETCHEST", Value = 52)]
		ERR_ACTIVITY_HASGETCHEST,

		[ProtoEnum(Name = "ERR_ACTIVITY_NOTENOUGHVALUE", Value = 53)]
		ERR_ACTIVITY_NOTENOUGHVALUE,

		[ProtoEnum(Name = "ERR_ACTIVITY_SPECIALCHESTCOUNTLIMIT", Value = 54)]
		ERR_ACTIVITY_SPECIALCHESTCOUNTLIMIT,

		[ProtoEnum(Name = "ERR_ARENA_ADDCOUNTLACKCOIN", Value = 55)]
		ERR_ARENA_ADDCOUNTLACKCOIN,

		[ProtoEnum(Name = "ERR_JADE_OPENJADELACKCOIN", Value = 56)]
		ERR_JADE_OPENJADELACKCOIN,

		[ProtoEnum(Name = "ERR_JADE_NOEMPTYSLOT", Value = 57)]
		ERR_JADE_NOEMPTYSLOT,

		[ProtoEnum(Name = "ERR_ITEM_NEED_DRAGONCOIN", Value = 58)]
		ERR_ITEM_NEED_DRAGONCOIN,

		[ProtoEnum(Name = "ERR_BUY_LIMIT", Value = 59)]
		ERR_BUY_LIMIT,

		[ProtoEnum(Name = "ERR_SWEEP_NOT_THREE_STAR", Value = 60)]
		ERR_SWEEP_NOT_THREE_STAR,

		[ProtoEnum(Name = "ERR_SHOP_ITEMNOTEXIST", Value = 61)]
		ERR_SHOP_ITEMNOTEXIST,

		[ProtoEnum(Name = "ERR_SHOP_LACKMONEY", Value = 62)]
		ERR_SHOP_LACKMONEY,

		[ProtoEnum(Name = "ERR_TEAM_ALREADY_INTEAM", Value = 63)]
		ERR_TEAM_ALREADY_INTEAM,

		[ProtoEnum(Name = "ERR_TEAM_NOT_EXIST", Value = 64)]
		ERR_TEAM_NOT_EXIST,

		[ProtoEnum(Name = "ERR_TEAM_FULL", Value = 65)]
		ERR_TEAM_FULL,

		[ProtoEnum(Name = "ERR_TEAM_WRONG_PASSWORD", Value = 66)]
		ERR_TEAM_WRONG_PASSWORD,

		[ProtoEnum(Name = "ERR_SCENE_TIMELIMIT", Value = 67)]
		ERR_SCENE_TIMELIMIT,

		[ProtoEnum(Name = "ERR_TEAM_EXPEDITIONID_NOT_EXIST", Value = 68)]
		ERR_TEAM_EXPEDITIONID_NOT_EXIST,

		[ProtoEnum(Name = "ERR_TEAM_LEVEL_REQUARE", Value = 69)]
		ERR_TEAM_LEVEL_REQUARE,

		[ProtoEnum(Name = "ERR_SCENE_COOLDOWN", Value = 70)]
		ERR_SCENE_COOLDOWN,

		[ProtoEnum(Name = "ERR_SKILL_MAXLEVEL", Value = 71)]
		ERR_SKILL_MAXLEVEL,

		[ProtoEnum(Name = "ERR_WORLDBOSS_DEAD", Value = 72)]
		ERR_WORLDBOSS_DEAD,

		[ProtoEnum(Name = "ERR_REINFORCE_LEVELLIMIT", Value = 73)]
		ERR_REINFORCE_LEVELLIMIT,

		[ProtoEnum(Name = "ERR_REINFORCE_LACKMONEY", Value = 74)]
		ERR_REINFORCE_LACKMONEY,

		[ProtoEnum(Name = "ERR_ARENA_REWARDTAKEN", Value = 75)]
		ERR_ARENA_REWARDTAKEN,

		[ProtoEnum(Name = "ERR_SKILL_PROFESSION_ERROR", Value = 76)]
		ERR_SKILL_PROFESSION_ERROR,

		[ProtoEnum(Name = "ERR_SKILL_NEED_PRESKILL", Value = 77)]
		ERR_SKILL_NEED_PRESKILL,

		[ProtoEnum(Name = "ERR_LOGIN_TIMEOUT", Value = 78)]
		ERR_LOGIN_TIMEOUT,

		[ProtoEnum(Name = "ERR_LOGIN_NOSERVER", Value = 79)]
		ERR_LOGIN_NOSERVER,

		[ProtoEnum(Name = "ERR_SHOP_LEVELLIMIT", Value = 80)]
		ERR_SHOP_LEVELLIMIT,

		[ProtoEnum(Name = "ERR_SHOP_PPTLIMIT", Value = 81)]
		ERR_SHOP_PPTLIMIT,

		[ProtoEnum(Name = "ERR_SHOP_COUNTLIMIT", Value = 82)]
		ERR_SHOP_COUNTLIMIT,

		[ProtoEnum(Name = "ERR_SHOP_DAILYCOUNTLIMIT", Value = 83)]
		ERR_SHOP_DAILYCOUNTLIMIT,

		[ProtoEnum(Name = "ERR_CHAT_LEVELLIMIT", Value = 84)]
		ERR_CHAT_LEVELLIMIT,

		[ProtoEnum(Name = "ERR_CHAT_LENGTHLIMIT", Value = 85)]
		ERR_CHAT_LENGTHLIMIT,

		[ProtoEnum(Name = "ERR_CHAT_TIMELIMIT", Value = 86)]
		ERR_CHAT_TIMELIMIT,

		[ProtoEnum(Name = "ERR_FASHOIN_ALREADY_EXIST", Value = 87)]
		ERR_FASHOIN_ALREADY_EXIST,

		[ProtoEnum(Name = "ERR_FASHION_NOT_EXIST", Value = 88)]
		ERR_FASHION_NOT_EXIST,

		[ProtoEnum(Name = "ERR_FRIEND_MAX", Value = 89)]
		ERR_FRIEND_MAX,

		[ProtoEnum(Name = "ERR_FRIEND_REPEATED", Value = 90)]
		ERR_FRIEND_REPEATED,

		[ProtoEnum(Name = "ERR_FRIEND_NOTEXIST", Value = 91)]
		ERR_FRIEND_NOTEXIST,

		[ProtoEnum(Name = "ERR_BLACK_INSELF", Value = 92)]
		ERR_BLACK_INSELF,

		[ProtoEnum(Name = "ERR_BLACK_INOTHER", Value = 93)]
		ERR_BLACK_INOTHER,

		[ProtoEnum(Name = "ERR_BLACK_NOTEXIST", Value = 94)]
		ERR_BLACK_NOTEXIST,

		[ProtoEnum(Name = "ERR_LOGIN_VERIFY_FAILED", Value = 95)]
		ERR_LOGIN_VERIFY_FAILED,

		[ProtoEnum(Name = "ERR_GUILD_NOT_EXIST", Value = 96)]
		ERR_GUILD_NOT_EXIST,

		[ProtoEnum(Name = "ERR_GUILD_NAME_EXIST", Value = 97)]
		ERR_GUILD_NAME_EXIST,

		[ProtoEnum(Name = "ERR_GUILD_NOT_IN_GUILD", Value = 98)]
		ERR_GUILD_NOT_IN_GUILD,

		[ProtoEnum(Name = "ERR_GUILD_ALREADY_IN_GUILD", Value = 99)]
		ERR_GUILD_ALREADY_IN_GUILD,

		[ProtoEnum(Name = "ERR_GUILD_NO_PERMISSION", Value = 100)]
		ERR_GUILD_NO_PERMISSION,

		[ProtoEnum(Name = "ERR_CHAPTERCHEST_ALREADY_FETCHED", Value = 101)]
		ERR_CHAPTERCHEST_ALREADY_FETCHED,

		[ProtoEnum(Name = "ERR_CHAPTERCHEST_NEEDSTAR", Value = 102)]
		ERR_CHAPTERCHEST_NEEDSTAR,

		[ProtoEnum(Name = "ERR_SESSION_KICKOFF", Value = 103)]
		ERR_SESSION_KICKOFF,

		[ProtoEnum(Name = "ERR_ALIVE_TIMEOUT", Value = 104)]
		ERR_ALIVE_TIMEOUT,

		[ProtoEnum(Name = "ERR_GS_CLOSED", Value = 105)]
		ERR_GS_CLOSED,

		[ProtoEnum(Name = "ERR_FASHIONCOMPOSE_LEVEL_REQ", Value = 106)]
		ERR_FASHIONCOMPOSE_LEVEL_REQ,

		[ProtoEnum(Name = "ERR_GUILD_FULL", Value = 107)]
		ERR_GUILD_FULL,

		[ProtoEnum(Name = "ERR_GUILD_PPT_REQ", Value = 108)]
		ERR_GUILD_PPT_REQ,

		[ProtoEnum(Name = "ERR_GUILD_WAITAPPROVAL", Value = 109)]
		ERR_GUILD_WAITAPPROVAL,

		[ProtoEnum(Name = "ERR_GUILD_MEMBER_NOT_EXIST", Value = 110)]
		ERR_GUILD_MEMBER_NOT_EXIST,

		[ProtoEnum(Name = "ERR_FLOWER_SELF", Value = 111)]
		ERR_FLOWER_SELF,

		[ProtoEnum(Name = "ERR_FLOWER_COUNTLIMIT", Value = 112)]
		ERR_FLOWER_COUNTLIMIT,

		[ProtoEnum(Name = "ERR_FLOWER_ROLELIMIT", Value = 113)]
		ERR_FLOWER_ROLELIMIT,

		[ProtoEnum(Name = "ERR_FLOWER_COSTLIMIT", Value = 114)]
		ERR_FLOWER_COSTLIMIT,

		[ProtoEnum(Name = "ERR_GUILDCARD_ALLCOUNTLIMIT", Value = 115)]
		ERR_GUILDCARD_ALLCOUNTLIMIT,

		[ProtoEnum(Name = "ERR_GUILDCARD_COUNTLIMIT", Value = 116)]
		ERR_GUILDCARD_COUNTLIMIT,

		[ProtoEnum(Name = "ERR_GUILDCARD_CHANGELIMIT", Value = 117)]
		ERR_GUILDCARD_CHANGELIMIT,

		[ProtoEnum(Name = "ERR_GUILDCHECKIN_LIMIT", Value = 118)]
		ERR_GUILDCHECKIN_LIMIT,

		[ProtoEnum(Name = "ERR_GUILDCHECKIN_MONEY", Value = 119)]
		ERR_GUILDCHECKIN_MONEY,

		[ProtoEnum(Name = "ERR_GUILDCHECKIN_TAKEN", Value = 120)]
		ERR_GUILDCHECKIN_TAKEN,

		[ProtoEnum(Name = "ERR_GUILDCHECKIN_BOXLIMIT", Value = 121)]
		ERR_GUILDCHECKIN_BOXLIMIT,

		[ProtoEnum(Name = "ERR_SCENE_NEED_PRESCENE", Value = 122)]
		ERR_SCENE_NEED_PRESCENE,

		[ProtoEnum(Name = "ERR_GUILDBONUS_NOTEXIST", Value = 123)]
		ERR_GUILDBONUS_NOTEXIST,

		[ProtoEnum(Name = "ERR_GUILDBONUS_ALREADYGET", Value = 124)]
		ERR_GUILDBONUS_ALREADYGET,

		[ProtoEnum(Name = "ERR_GUILDBONUS_EXCEED", Value = 125)]
		ERR_GUILDBONUS_EXCEED,

		[ProtoEnum(Name = "ERR_GUILD_OPENLIMIT", Value = 126)]
		ERR_GUILD_OPENLIMIT,

		[ProtoEnum(Name = "ERR_SHOP_OPENLIMIT", Value = 127)]
		ERR_SHOP_OPENLIMIT,

		[ProtoEnum(Name = "ERR_GUILDCHECKIN_ALLCOUNT", Value = 128)]
		ERR_GUILDCHECKIN_ALLCOUNT,

		[ProtoEnum(Name = "ERR_TEAM_EXPEDITION_DAYCOUNT", Value = 129)]
		ERR_TEAM_EXPEDITION_DAYCOUNT,

		[ProtoEnum(Name = "ERR_TEAM_GUILD_DAYCOUNT", Value = 130)]
		ERR_TEAM_GUILD_DAYCOUNT,

		[ProtoEnum(Name = "ERR_TEAM_NEST_DAYCOUNT", Value = 131)]
		ERR_TEAM_NEST_DAYCOUNT,

		[ProtoEnum(Name = "ERR_GUILD_LEVEL_REQ", Value = 132)]
		ERR_GUILD_LEVEL_REQ,

		[ProtoEnum(Name = "ERR_TEAM_NOT_OPENTIME", Value = 133)]
		ERR_TEAM_NOT_OPENTIME,

		[ProtoEnum(Name = "ERR_TEAM_NEED_ATLEAST_2_MEMBER", Value = 134)]
		ERR_TEAM_NEED_ATLEAST_2_MEMBER,

		[ProtoEnum(Name = "ERR_TEAM_ONLY_LEADER_CAN_KICK", Value = 135)]
		ERR_TEAM_ONLY_LEADER_CAN_KICK,

		[ProtoEnum(Name = "ERR_TEAM_MEMBER_NOT_EXIST", Value = 136)]
		ERR_TEAM_MEMBER_NOT_EXIST,

		[ProtoEnum(Name = "ERR_SKILL_GUILD_CONTRIBUTE", Value = 137)]
		ERR_SKILL_GUILD_CONTRIBUTE,

		[ProtoEnum(Name = "ERR_REWARD_TAKEN", Value = 138)]
		ERR_REWARD_TAKEN,

		[ProtoEnum(Name = "ERR_REWARD_LIMIT", Value = 139)]
		ERR_REWARD_LIMIT,

		[ProtoEnum(Name = "ERR_REWARD_NOTEXIST", Value = 140)]
		ERR_REWARD_NOTEXIST,

		[ProtoEnum(Name = "ERR_GUILD_VICE_FULL", Value = 141)]
		ERR_GUILD_VICE_FULL,

		[ProtoEnum(Name = "ERR_GUILD_OFFICER_FULL", Value = 142)]
		ERR_GUILD_OFFICER_FULL,

		[ProtoEnum(Name = "ERR_GUILD_ELITE_FULL", Value = 143)]
		ERR_GUILD_ELITE_FULL,

		[ProtoEnum(Name = "ERR_TEAM_MEMBER_NOT_ONLINE", Value = 144)]
		ERR_TEAM_MEMBER_NOT_ONLINE,

		[ProtoEnum(Name = "ERR_TEAM_DISAGREE_BATTLE", Value = 145)]
		ERR_TEAM_DISAGREE_BATTLE,

		[ProtoEnum(Name = "ERR_TEAM_ONLY_LEADER_CAN_STARTBATTLE", Value = 146)]
		ERR_TEAM_ONLY_LEADER_CAN_STARTBATTLE,

		[ProtoEnum(Name = "ERR_TEAM_MATCHING", Value = 147)]
		ERR_TEAM_MATCHING,

		[ProtoEnum(Name = "ERR_ROLE_NOT_ONLINE", Value = 148)]
		ERR_ROLE_NOT_ONLINE,

		[ProtoEnum(Name = "ERR_TEAM_ONLY_LEADER_CAN_DO", Value = 149)]
		ERR_TEAM_ONLY_LEADER_CAN_DO,

		[ProtoEnum(Name = "ERR_LACKCOIN", Value = 150)]
		ERR_LACKCOIN,

		[ProtoEnum(Name = "ERR_LACKDIAMOND", Value = 151)]
		ERR_LACKDIAMOND,

		[ProtoEnum(Name = "ERR_SMELTING_INVALID", Value = 152)]
		ERR_SMELTING_INVALID,

		[ProtoEnum(Name = "ERR_SMELTING_TRANSINVALID", Value = 153)]
		ERR_SMELTING_TRANSINVALID,

		[ProtoEnum(Name = "ERR_GUILD_NAME_TOO_SHORT", Value = 154)]
		ERR_GUILD_NAME_TOO_SHORT,

		[ProtoEnum(Name = "ERR_GUILD_NAME_TOO_LONG", Value = 155)]
		ERR_GUILD_NAME_TOO_LONG,

		[ProtoEnum(Name = "ERR_TEAM_NOT_IN_HALL", Value = 156)]
		ERR_TEAM_NOT_IN_HALL,

		[ProtoEnum(Name = "ERR_TEAM_IN_BATTLE", Value = 157)]
		ERR_TEAM_IN_BATTLE,

		[ProtoEnum(Name = "ERR_TEAM_VOTE", Value = 158)]
		ERR_TEAM_VOTE,

		[ProtoEnum(Name = "ERR_TEAM_STATE_ERROR", Value = 159)]
		ERR_TEAM_STATE_ERROR,

		[ProtoEnum(Name = "ERR_TEAM_INVITE_ROLE_IS_IN_BATTLE", Value = 160)]
		ERR_TEAM_INVITE_ROLE_IS_IN_BATTLE,

		[ProtoEnum(Name = "ERR_ITEM_COOLDOWN", Value = 161)]
		ERR_ITEM_COOLDOWN,

		[ProtoEnum(Name = "ERR_LOGIN_FORBID", Value = 162)]
		ERR_LOGIN_FORBID,

		[ProtoEnum(Name = "ERR_LOGIN_MAXNUM", Value = 163)]
		ERR_LOGIN_MAXNUM,

		[ProtoEnum(Name = "ERR_SCENE_NEED_PRETASK", Value = 164)]
		ERR_SCENE_NEED_PRETASK,

		[ProtoEnum(Name = "ERR_NAME_HAS_INVALID_CHAR", Value = 165)]
		ERR_NAME_HAS_INVALID_CHAR,

		[ProtoEnum(Name = "ERR_SMELTING_LACKMONEY", Value = 166)]
		ERR_SMELTING_LACKMONEY,

		[ProtoEnum(Name = "ERR_OTHER_GAOJIGU_NOTOPEN", Value = 167)]
		ERR_OTHER_GAOJIGU_NOTOPEN,

		[ProtoEnum(Name = "ERR_FISHING_NUMNOTENOUGH", Value = 168)]
		ERR_FISHING_NUMNOTENOUGH,

		[ProtoEnum(Name = "ERR_FISHING_ALREADYSEAT", Value = 169)]
		ERR_FISHING_ALREADYSEAT,

		[ProtoEnum(Name = "ERR_FISHING_SEATNOTEMPTY", Value = 170)]
		ERR_FISHING_SEATNOTEMPTY,

		[ProtoEnum(Name = "ERR_SLOTATTR_NOEQUIP", Value = 171)]
		ERR_SLOTATTR_NOEQUIP,

		[ProtoEnum(Name = "ERR_SLOTATTR_MONEYLIMIT", Value = 172)]
		ERR_SLOTATTR_MONEYLIMIT,

		[ProtoEnum(Name = "ERR_SLOTATTR_LEVELLIMIT", Value = 173)]
		ERR_SLOTATTR_LEVELLIMIT,

		[ProtoEnum(Name = "ERR_PK_NOMATCH", Value = 174)]
		ERR_PK_NOMATCH,

		[ProtoEnum(Name = "ERR_ITEM_WRONG_PROFESSION", Value = 175)]
		ERR_ITEM_WRONG_PROFESSION,

		[ProtoEnum(Name = "ERR_SKILL_NOT_MATCH", Value = 176)]
		ERR_SKILL_NOT_MATCH,

		[ProtoEnum(Name = "ERR_TSHOW_LEVEL_NOTENOUGH", Value = 177)]
		ERR_TSHOW_LEVEL_NOTENOUGH,

		[ProtoEnum(Name = "ERR_TRANSFER_LACKMONEY", Value = 178)]
		ERR_TRANSFER_LACKMONEY,

		[ProtoEnum(Name = "ERR_AUCT_HAVEBIDDING", Value = 179)]
		ERR_AUCT_HAVEBIDDING,

		[ProtoEnum(Name = "ERR_AUCT_ITEMOUTSALE", Value = 180)]
		ERR_AUCT_ITEMOUTSALE,

		[ProtoEnum(Name = "ERR_AUCT_PRICECHAGE", Value = 181)]
		ERR_AUCT_PRICECHAGE,

		[ProtoEnum(Name = "ERR_AUCT_SURPASSSELF", Value = 182)]
		ERR_AUCT_SURPASSSELF,

		[ProtoEnum(Name = "ERR_AUCT_POINTLESS", Value = 183)]
		ERR_AUCT_POINTLESS,

		[ProtoEnum(Name = "ERR_AUCT_DRAGONCOINLESS", Value = 184)]
		ERR_AUCT_DRAGONCOINLESS,

		[ProtoEnum(Name = "ERR_AUCT_BUYSELF", Value = 185)]
		ERR_AUCT_BUYSELF,

		[ProtoEnum(Name = "ERR_ALREADY_IN_CAMP", Value = 186)]
		ERR_ALREADY_IN_CAMP,

		[ProtoEnum(Name = "ERR_NOT_IN_CAMP", Value = 187)]
		ERR_NOT_IN_CAMP,

		[ProtoEnum(Name = "ERR_AUCT_ONSALEMAX", Value = 188)]
		ERR_AUCT_ONSALEMAX,

		[ProtoEnum(Name = "ERR_AUCT_COMMONERR", Value = 189)]
		ERR_AUCT_COMMONERR,

		[ProtoEnum(Name = "ERR_AUCT_ITEMSALED", Value = 190)]
		ERR_AUCT_ITEMSALED,

		[ProtoEnum(Name = "ERR_SCENE_NOT_IN_CONFIG", Value = 191)]
		ERR_SCENE_NOT_IN_CONFIG,

		[ProtoEnum(Name = "ERR_GAOJIGU_MODEL_DUPLICATE_FASHIONID", Value = 192)]
		ERR_GAOJIGU_MODEL_DUPLICATE_FASHIONID,

		[ProtoEnum(Name = "ERR_TEAMBUY_COUNT_MAX", Value = 193)]
		ERR_TEAMBUY_COUNT_MAX,

		[ProtoEnum(Name = "ERR_TEAMBUY_DIAMOND_LESS", Value = 194)]
		ERR_TEAMBUY_DIAMOND_LESS,

		[ProtoEnum(Name = "ERR_ADDFRIEND_DUMMYROLE", Value = 195)]
		ERR_ADDFRIEND_DUMMYROLE,

		[ProtoEnum(Name = "ERR_VERSION_FAILED", Value = 196)]
		ERR_VERSION_FAILED,

		[ProtoEnum(Name = "ERR_EXPBACK_ALREADYGET", Value = 197)]
		ERR_EXPBACK_ALREADYGET,

		[ProtoEnum(Name = "ERR_PK_OPENTIME", Value = 198)]
		ERR_PK_OPENTIME,

		[ProtoEnum(Name = "ERR_ITEM_NEED_DIAMOND", Value = 199)]
		ERR_ITEM_NEED_DIAMOND,

		[ProtoEnum(Name = "ERR_WORD_FORBID", Value = 200)]
		ERR_WORD_FORBID,

		[ProtoEnum(Name = "ERR_TEAM_TOWER_DAYCOUNT", Value = 201)]
		ERR_TEAM_TOWER_DAYCOUNT,

		[ProtoEnum(Name = "ERR_AUCTGOLDLESS", Value = 202)]
		ERR_AUCTGOLDLESS,

		[ProtoEnum(Name = "ERR_ILLEGAL_CODE", Value = 203)]
		ERR_ILLEGAL_CODE,

		[ProtoEnum(Name = "ERR_GUILD_CHECKINBONUS_TIMEERROR", Value = 204)]
		ERR_GUILD_CHECKINBONUS_TIMEERROR,

		[ProtoEnum(Name = "ERR_GUILD_CHECKINBONUS_ASKTOOMUCH", Value = 205)]
		ERR_GUILD_CHECKINBONUS_ASKTOOMUCH,

		[ProtoEnum(Name = "ERR_TEAM_NOJOININBATTLE", Value = 206)]
		ERR_TEAM_NOJOININBATTLE,

		[ProtoEnum(Name = "ERR_REGISTER_NUM_LIMIT", Value = 207)]
		ERR_REGISTER_NUM_LIMIT,

		[ProtoEnum(Name = "ERR_FRIEND_MAXOTHER", Value = 208)]
		ERR_FRIEND_MAXOTHER,

		[ProtoEnum(Name = "ERR_FRIEND_SENDLIMIT", Value = 209)]
		ERR_FRIEND_SENDLIMIT,

		[ProtoEnum(Name = "ERR_FRIEND_TAKENLIMIT", Value = 210)]
		ERR_FRIEND_TAKENLIMIT,

		[ProtoEnum(Name = "ERR_ROLE_NOTEXIST", Value = 211)]
		ERR_ROLE_NOTEXIST,

		[ProtoEnum(Name = "ERR_RANDOMFRIEND_CD", Value = 212)]
		ERR_RANDOMFRIEND_CD,

		[ProtoEnum(Name = "ERR_ENHANCE_TRANSLEVEL", Value = 213)]
		ERR_ENHANCE_TRANSLEVEL,

		[ProtoEnum(Name = "ERR_ENHANCE_TRANSPOS", Value = 214)]
		ERR_ENHANCE_TRANSPOS,

		[ProtoEnum(Name = "ERR_GUILD_LVL_LIMIT", Value = 215)]
		ERR_GUILD_LVL_LIMIT,

		[ProtoEnum(Name = "ERR_FRIEND_HASSEND", Value = 216)]
		ERR_FRIEND_HASSEND,

		[ProtoEnum(Name = "ERR_GUILD_APPLYFULL", Value = 217)]
		ERR_GUILD_APPLYFULL,

		[ProtoEnum(Name = "ERR_BLACK_CHAT", Value = 218)]
		ERR_BLACK_CHAT,

		[ProtoEnum(Name = "ERR_PVP_ROLE_INBATTLE", Value = 219)]
		ERR_PVP_ROLE_INBATTLE,

		[ProtoEnum(Name = "ERR_FRIEND_SELF", Value = 220)]
		ERR_FRIEND_SELF,

		[ProtoEnum(Name = "ERR_BLACK_MAX", Value = 221)]
		ERR_BLACK_MAX,

		[ProtoEnum(Name = "ERR_EMBLEM_NOIDENTIFY", Value = 222)]
		ERR_EMBLEM_NOIDENTIFY,

		[ProtoEnum(Name = "ERR_EMBLEM_NOTHIRDSLOT", Value = 223)]
		ERR_EMBLEM_NOTHIRDSLOT,

		[ProtoEnum(Name = "ERR_EMBLEM_CANTIDENTIFY", Value = 224)]
		ERR_EMBLEM_CANTIDENTIFY,

		[ProtoEnum(Name = "GUILD_SKILL_STUDY_LEVEL_LIMIT", Value = 225)]
		GUILD_SKILL_STUDY_LEVEL_LIMIT,

		[ProtoEnum(Name = "GUILD_SKILL_GUILD_LEVEL_LIMIT", Value = 226)]
		GUILD_SKILL_GUILD_LEVEL_LIMIT,

		[ProtoEnum(Name = "ERR_GUILD_EXP_LIMIT", Value = 227)]
		ERR_GUILD_EXP_LIMIT,

		[ProtoEnum(Name = "ERR_REVIVE_MAXNUM", Value = 228)]
		ERR_REVIVE_MAXNUM,

		[ProtoEnum(Name = "ERR_QA_OVER_NAME_TIME", Value = 229)]
		ERR_QA_OVER_NAME_TIME,

		[ProtoEnum(Name = "ERR_QA_IN_OTHER_TYPE", Value = 230)]
		ERR_QA_IN_OTHER_TYPE,

		[ProtoEnum(Name = "ERR_JADE_MINEQUIPLEVEL", Value = 231)]
		ERR_JADE_MINEQUIPLEVEL,

		[ProtoEnum(Name = "ERR_SWEEP_POWERPOINT_LESS", Value = 232)]
		ERR_SWEEP_POWERPOINT_LESS,

		[ProtoEnum(Name = "ERR_SWEEP_TICKET_LESS", Value = 233)]
		ERR_SWEEP_TICKET_LESS,

		[ProtoEnum(Name = "ERR_ACCOUNT_INVALID", Value = 234)]
		ERR_ACCOUNT_INVALID,

		[ProtoEnum(Name = "ERR_JADE_WRONGTYPE", Value = 235)]
		ERR_JADE_WRONGTYPE,

		[ProtoEnum(Name = "ERR_SHOP_TIMELIMIT", Value = 236)]
		ERR_SHOP_TIMELIMIT,

		[ProtoEnum(Name = "ERR_SHOP_VIPLIMIT", Value = 237)]
		ERR_SHOP_VIPLIMIT,

		[ProtoEnum(Name = "ERR_SHOP_ARENALIMIT", Value = 238)]
		ERR_SHOP_ARENALIMIT,

		[ProtoEnum(Name = "ERR_SHOP_PKLIMIT", Value = 239)]
		ERR_SHOP_PKLIMIT,

		[ProtoEnum(Name = "ERR_SHOP_GUILDLIMIT", Value = 240)]
		ERR_SHOP_GUILDLIMIT,

		[ProtoEnum(Name = "ERR_AUDIO_NOT_EXIST", Value = 241)]
		ERR_AUDIO_NOT_EXIST,

		[ProtoEnum(Name = "ERR_SHOP_INVALID", Value = 242)]
		ERR_SHOP_INVALID,

		[ProtoEnum(Name = "ERR_WATCH_LIVEISOVER", Value = 243)]
		ERR_WATCH_LIVEISOVER,

		[ProtoEnum(Name = "ERR_WATCH_LIVEISFULL", Value = 244)]
		ERR_WATCH_LIVEISFULL,

		[ProtoEnum(Name = "ERR_TOWER_INSWEEP", Value = 245)]
		ERR_TOWER_INSWEEP,

		[ProtoEnum(Name = "ERR_TOWER_FLOOR_NOTENOUGH", Value = 246)]
		ERR_TOWER_FLOOR_NOTENOUGH,

		[ProtoEnum(Name = "ERR_DRAGON_TICKET_NOTENOUGH", Value = 247)]
		ERR_DRAGON_TICKET_NOTENOUGH,

		[ProtoEnum(Name = "ERR_WATCH_WAIT", Value = 248)]
		ERR_WATCH_WAIT,

		[ProtoEnum(Name = "ERR_OP_EXP_NOT_OPEN", Value = 249)]
		ERR_OP_EXP_NOT_OPEN,

		[ProtoEnum(Name = "ERR_TEAM_GODDESS_DAYCOUNT", Value = 250)]
		ERR_TEAM_GODDESS_DAYCOUNT,

		[ProtoEnum(Name = "ERR_TEAM_SEAL_TYPE", Value = 251)]
		ERR_TEAM_SEAL_TYPE,

		[ProtoEnum(Name = "ERR_DRAGON_PROGRESS_INVALID", Value = 252)]
		ERR_DRAGON_PROGRESS_INVALID,

		[ProtoEnum(Name = "ERR_TEAMBUY_DRAGONCOIN_LESS", Value = 253)]
		ERR_TEAMBUY_DRAGONCOIN_LESS,

		[ProtoEnum(Name = "ERR_JADE_REPLACE", Value = 254)]
		ERR_JADE_REPLACE,

		[ProtoEnum(Name = "ERR_PVP_TEAM_MATCH", Value = 255)]
		ERR_PVP_TEAM_MATCH,

		[ProtoEnum(Name = "ERR_GS_UNREADY", Value = 256)]
		ERR_GS_UNREADY,

		[ProtoEnum(Name = "ERR_INVALID_REQUEST", Value = 257)]
		ERR_INVALID_REQUEST,

		[ProtoEnum(Name = "ERR_PET_NOT_EXIST", Value = 258)]
		ERR_PET_NOT_EXIST,

		[ProtoEnum(Name = "ERR_PE_CAN_NOT_RELEASE", Value = 259)]
		ERR_PE_CAN_NOT_RELEASE,

		[ProtoEnum(Name = "ERR_PETSYS_NOT_OPEN", Value = 260)]
		ERR_PETSYS_NOT_OPEN,

		[ProtoEnum(Name = "ERR_PET_SEAT_NOT_ENOUGH", Value = 261)]
		ERR_PET_SEAT_NOT_ENOUGH,

		[ProtoEnum(Name = "ERR_ACCOUNT_QUEUING", Value = 262)]
		ERR_ACCOUNT_QUEUING,

		[ProtoEnum(Name = "ERR_TITLE_MAX", Value = 263)]
		ERR_TITLE_MAX,

		[ProtoEnum(Name = "ERR_TITLE_LACKITEM", Value = 264)]
		ERR_TITLE_LACKITEM,

		[ProtoEnum(Name = "ERR_TITLE_PPTLIMIT", Value = 265)]
		ERR_TITLE_PPTLIMIT,

		[ProtoEnum(Name = "ERR_BLACK_REPEATED", Value = 266)]
		ERR_BLACK_REPEATED,

		[ProtoEnum(Name = "ERR_BLACK_SELF", Value = 267)]
		ERR_BLACK_SELF,

		[ProtoEnum(Name = "ERR_TEAM_LEADER_NOTHELPER", Value = 268)]
		ERR_TEAM_LEADER_NOTHELPER,

		[ProtoEnum(Name = "ERR_PET_IS_FULL", Value = 269)]
		ERR_PET_IS_FULL,

		[ProtoEnum(Name = "ERR_IBSHOP_LACKGOODS", Value = 270)]
		ERR_IBSHOP_LACKGOODS,

		[ProtoEnum(Name = "ERR_IBSHOP_LIMITCOUNT", Value = 271)]
		ERR_IBSHOP_LIMITCOUNT,

		[ProtoEnum(Name = "ERR_IBSHOP_LACKDIAMOND", Value = 272)]
		ERR_IBSHOP_LACKDIAMOND,

		[ProtoEnum(Name = "ERR_IBSHOP_LACKDRAGON", Value = 273)]
		ERR_IBSHOP_LACKDRAGON,

		[ProtoEnum(Name = "ERR_CHAT_PUNISH", Value = 274)]
		ERR_CHAT_PUNISH,

		[ProtoEnum(Name = "ERR_LOCKED_ROLE", Value = 275)]
		ERR_LOCKED_ROLE,

		[ProtoEnum(Name = "ERR_IBSHOP_ERRPARAM", Value = 276)]
		ERR_IBSHOP_ERRPARAM,

		[ProtoEnum(Name = "ERR_IBSHOP_BUYLV", Value = 277)]
		ERR_IBSHOP_BUYLV,

		[ProtoEnum(Name = "ERR_SPRITE_NOTFIND", Value = 278)]
		ERR_SPRITE_NOTFIND,

		[ProtoEnum(Name = "ERR_SPRITE_LEVELMAX", Value = 279)]
		ERR_SPRITE_LEVELMAX,

		[ProtoEnum(Name = "ERR_SPRITE_EVOLUTION_LEVELMAX", Value = 280)]
		ERR_SPRITE_EVOLUTION_LEVELMAX,

		[ProtoEnum(Name = "ERR_SPRITE_EVOLUTION_LEVELLIMIT", Value = 281)]
		ERR_SPRITE_EVOLUTION_LEVELLIMIT,

		[ProtoEnum(Name = "ERR_SPRITE_EVOLUTION_LACKOFCOST", Value = 282)]
		ERR_SPRITE_EVOLUTION_LACKOFCOST,

		[ProtoEnum(Name = "ERR_SPRITE_AWAKE_LACKOFCOST", Value = 283)]
		ERR_SPRITE_AWAKE_LACKOFCOST,

		[ProtoEnum(Name = "ERR_SPRITE_LEVELUP_LACKOFCOST", Value = 284)]
		ERR_SPRITE_LEVELUP_LACKOFCOST,

		[ProtoEnum(Name = "ERR_SPRITE_ALREADY_INFIGHT", Value = 285)]
		ERR_SPRITE_ALREADY_INFIGHT,

		[ProtoEnum(Name = "ERR_SPRITE_INFIGHT_FULL", Value = 286)]
		ERR_SPRITE_INFIGHT_FULL,

		[ProtoEnum(Name = "ERR_SPRITE_ALREADY_OUTFIGHT", Value = 287)]
		ERR_SPRITE_ALREADY_OUTFIGHT,

		[ProtoEnum(Name = "ERR_REVIVE_ITEMLIMIT", Value = 288)]
		ERR_REVIVE_ITEMLIMIT,

		[ProtoEnum(Name = "ERR_REVIVE_MONEYLIMIT", Value = 289)]
		ERR_REVIVE_MONEYLIMIT,

		[ProtoEnum(Name = "ERR_ENHANCE_NO_EQUIP_CAN_TRANSFORM", Value = 290)]
		ERR_ENHANCE_NO_EQUIP_CAN_TRANSFORM,

		[ProtoEnum(Name = "ERR_IBSHOP_VIPLEVEL", Value = 291)]
		ERR_IBSHOP_VIPLEVEL,

		[ProtoEnum(Name = "ERR_IBSHOP_OPENGROUP", Value = 292)]
		ERR_IBSHOP_OPENGROUP,

		[ProtoEnum(Name = "ERR_SPRITE_INFIGHT_SAMETYPE", Value = 293)]
		ERR_SPRITE_INFIGHT_SAMETYPE,

		[ProtoEnum(Name = "ERR_SMELT_MINLEVEL", Value = 294)]
		ERR_SMELT_MINLEVEL,

		[ProtoEnum(Name = "ERR_JADE_GOLDNOTENOUGH", Value = 295)]
		ERR_JADE_GOLDNOTENOUGH,

		[ProtoEnum(Name = "ATLAS_CARD_NOT_ENOUGH", Value = 296)]
		ATLAS_CARD_NOT_ENOUGH,

		[ProtoEnum(Name = "ERR_AUCT_ITEM_LESS", Value = 297)]
		ERR_AUCT_ITEM_LESS,

		[ProtoEnum(Name = "ERR_AUCT_ITEM_LOCK", Value = 298)]
		ERR_AUCT_ITEM_LOCK,

		[ProtoEnum(Name = "ERR_AUCT_PRICE_NOTCHANGE", Value = 299)]
		ERR_AUCT_PRICE_NOTCHANGE,

		[ProtoEnum(Name = "ERR_LEVELSEAL_PROP_NOT_ENGOUTH", Value = 300)]
		ERR_LEVELSEAL_PROP_NOT_ENGOUTH,

		[ProtoEnum(Name = "ERR_AUCT_AUTOREFRESH_TIME", Value = 301)]
		ERR_AUCT_AUTOREFRESH_TIME,

		[ProtoEnum(Name = "ERR_ATLAS_NOT_BREAK", Value = 302)]
		ERR_ATLAS_NOT_BREAK,

		[ProtoEnum(Name = "ERR_LOGIN_NOT_IN_WHITE_LIST", Value = 303)]
		ERR_LOGIN_NOT_IN_WHITE_LIST,

		[ProtoEnum(Name = "ERR_TEAM_NOT_PASS", Value = 304)]
		ERR_TEAM_NOT_PASS,

		[ProtoEnum(Name = "ERR_QA_ALEADY_IN_ROOM", Value = 500)]
		ERR_QA_ALEADY_IN_ROOM = 500,

		[ProtoEnum(Name = "ERR_QA_NO_DATA", Value = 501)]
		ERR_QA_NO_DATA,

		[ProtoEnum(Name = "ERR_QA_LEVEL_NOT_ENOUGH", Value = 502)]
		ERR_QA_LEVEL_NOT_ENOUGH,

		[ProtoEnum(Name = "ERR_QA_NOT_IN_TIME", Value = 503)]
		ERR_QA_NOT_IN_TIME,

		[ProtoEnum(Name = "ERR_QA_NO_GUILD", Value = 504)]
		ERR_QA_NO_GUILD,

		[ProtoEnum(Name = "ERR_QA_NO_COUNT", Value = 505)]
		ERR_QA_NO_COUNT,

		[ProtoEnum(Name = "ERR_TASK_NOT_ACCEPT", Value = 510)]
		ERR_TASK_NOT_ACCEPT = 510,

		[ProtoEnum(Name = "ERR_TASK_ALREADY_TAKE", Value = 511)]
		ERR_TASK_ALREADY_TAKE,

		[ProtoEnum(Name = "ERR_TASK_NOT_FOUND", Value = 512)]
		ERR_TASK_NOT_FOUND,

		[ProtoEnum(Name = "ERR_TASK_NOT_FINISH", Value = 513)]
		ERR_TASK_NOT_FINISH,

		[ProtoEnum(Name = "ERR_TASK_NO_TABLE", Value = 514)]
		ERR_TASK_NO_TABLE,

		[ProtoEnum(Name = "ERR_GUILD_LADDER_NOT_OPEN", Value = 515)]
		ERR_GUILD_LADDER_NOT_OPEN,

		[ProtoEnum(Name = "ERR_GARDEN_NOTEXIST_FARMLAND", Value = 516)]
		ERR_GARDEN_NOTEXIST_FARMLAND,

		[ProtoEnum(Name = "ERR_GARDEN_NOHARVESTSTATE", Value = 517)]
		ERR_GARDEN_NOHARVESTSTATE,

		[ProtoEnum(Name = "ERR_GARDEN_STEALEDTIMES_EXCEED", Value = 518)]
		ERR_GARDEN_STEALEDTIMES_EXCEED,

		[ProtoEnum(Name = "ERR_GARDEN_NOTEXIST_SEEDID", Value = 519)]
		ERR_GARDEN_NOTEXIST_SEEDID,

		[ProtoEnum(Name = "ERR_GARDEN_NOTEXIST_SPRITE", Value = 520)]
		ERR_GARDEN_NOTEXIST_SPRITE,

		[ProtoEnum(Name = "ERR_SKYCITY_NOT_OPEN", Value = 521)]
		ERR_SKYCITY_NOT_OPEN,

		[ProtoEnum(Name = "ERR_GMF_UP_INCOOL", Value = 522)]
		ERR_GMF_UP_INCOOL,

		[ProtoEnum(Name = "ERR_GMF_UP_FULL", Value = 523)]
		ERR_GMF_UP_FULL,

		[ProtoEnum(Name = "ERR_QA_NO_GUILD_ROOM", Value = 524)]
		ERR_QA_NO_GUILD_ROOM,

		[ProtoEnum(Name = "ERR_TEAM_ALREADY_INOTHERTEAM", Value = 525)]
		ERR_TEAM_ALREADY_INOTHERTEAM,

		[ProtoEnum(Name = "ERR_TEAM_IDIP", Value = 526)]
		ERR_TEAM_IDIP,

		[ProtoEnum(Name = "ERR_COMMENDWATCH_COUNTLIMIT", Value = 527)]
		ERR_COMMENDWATCH_COUNTLIMIT,

		[ProtoEnum(Name = "ERR_CARDMATCH_BEGINFAILED", Value = 528)]
		ERR_CARDMATCH_BEGINFAILED,

		[ProtoEnum(Name = "ERR_CARDMATCH_NOBEGIN", Value = 529)]
		ERR_CARDMATCH_NOBEGIN,

		[ProtoEnum(Name = "ERR_CARDMATCH_ENDSOON", Value = 530)]
		ERR_CARDMATCH_ENDSOON,

		[ProtoEnum(Name = "ERR_CARDMATCH_CHANGELIMIT", Value = 531)]
		ERR_CARDMATCH_CHANGELIMIT,

		[ProtoEnum(Name = "ERR_SKILL_PREPOINTLIMIT", Value = 532)]
		ERR_SKILL_PREPOINTLIMIT,

		[ProtoEnum(Name = "ERR_SPACTIVITY_TASK_NOT_COMPLETE", Value = 533)]
		ERR_SPACTIVITY_TASK_NOT_COMPLETE,

		[ProtoEnum(Name = "ERR_SPACTIVITY_TASK_GET", Value = 534)]
		ERR_SPACTIVITY_TASK_GET,

		[ProtoEnum(Name = "ERR_SPACTIVITY_NOPRIZE", Value = 535)]
		ERR_SPACTIVITY_NOPRIZE,

		[ProtoEnum(Name = "ERR_SPACTIVITY_NOTPRIZETIME", Value = 536)]
		ERR_SPACTIVITY_NOTPRIZETIME,

		[ProtoEnum(Name = "ERR_SPACTIVITY_NOTENOUGH_MONEY", Value = 537)]
		ERR_SPACTIVITY_NOTENOUGH_MONEY,

		[ProtoEnum(Name = "ERR_SPACTIVITY_PRIZE_GET", Value = 538)]
		ERR_SPACTIVITY_PRIZE_GET,

		[ProtoEnum(Name = "ERR_GARDEN_PLANT_CD", Value = 539)]
		ERR_GARDEN_PLANT_CD,

		[ProtoEnum(Name = "ERR_GARDEN_COOKING_EXCEED", Value = 540)]
		ERR_GARDEN_COOKING_EXCEED,

		[ProtoEnum(Name = "ERR_GARDEN_COOKINGLEVEL_LOW", Value = 541)]
		ERR_GARDEN_COOKINGLEVEL_LOW,

		[ProtoEnum(Name = "ERR_GARDEN_PLANT_CUL_ERR", Value = 542)]
		ERR_GARDEN_PLANT_CUL_ERR,

		[ProtoEnum(Name = "ERR_GARDEN_ERR_SEED", Value = 543)]
		ERR_GARDEN_ERR_SEED,

		[ProtoEnum(Name = "ERR_GARDEN_NOSEED", Value = 544)]
		ERR_GARDEN_NOSEED,

		[ProtoEnum(Name = "ERR_GARDEN_NOALLOW", Value = 545)]
		ERR_GARDEN_NOALLOW,

		[ProtoEnum(Name = "ERR_GMF_NOPOWER_KICK_LEADER", Value = 546)]
		ERR_GMF_NOPOWER_KICK_LEADER,

		[ProtoEnum(Name = "ERR_SPRITE_ALREADY_ISLEADER", Value = 547)]
		ERR_SPRITE_ALREADY_ISLEADER,

		[ProtoEnum(Name = "ERR_SPRITE_AWAKE_ROLE_LEVELLIMIT", Value = 548)]
		ERR_SPRITE_AWAKE_ROLE_LEVELLIMIT,

		[ProtoEnum(Name = "ERR_SPRITE_EVOLUTION_ROLE_LEVELLIMIT", Value = 549)]
		ERR_SPRITE_EVOLUTION_ROLE_LEVELLIMIT,

		[ProtoEnum(Name = "ERR_GUILD_ALREADY_BIND", Value = 550)]
		ERR_GUILD_ALREADY_BIND,

		[ProtoEnum(Name = "ERR_GUILD_NOT_BIND", Value = 551)]
		ERR_GUILD_NOT_BIND,

		[ProtoEnum(Name = "ERR_ALREADY_IN_QQGROUP", Value = 552)]
		ERR_ALREADY_IN_QQGROUP,

		[ProtoEnum(Name = "ERR_INSPIRE_COOLDOWN", Value = 553)]
		ERR_INSPIRE_COOLDOWN,

		[ProtoEnum(Name = "ERR_SKYCITY_IN_TEAM", Value = 554)]
		ERR_SKYCITY_IN_TEAM,

		[ProtoEnum(Name = "ERR_SKYCITY_TEAM_OUTTIME", Value = 555)]
		ERR_SKYCITY_TEAM_OUTTIME,

		[ProtoEnum(Name = "ERR_GMF_DOWN_FIGHTING", Value = 556)]
		ERR_GMF_DOWN_FIGHTING,

		[ProtoEnum(Name = "ERR_GMF_DOWN_HAVEFAILED", Value = 557)]
		ERR_GMF_DOWN_HAVEFAILED,

		[ProtoEnum(Name = "ERR_JADE_SAME_TYPE", Value = 558)]
		ERR_JADE_SAME_TYPE,

		[ProtoEnum(Name = "ERR_CHAT_BLACK_INSELF", Value = 559)]
		ERR_CHAT_BLACK_INSELF,

		[ProtoEnum(Name = "ERR_CHAT_BLACK_INOTHER", Value = 560)]
		ERR_CHAT_BLACK_INOTHER,

		[ProtoEnum(Name = "ERR_GARDEN_QUESTS_NOENOUGH", Value = 561)]
		ERR_GARDEN_QUESTS_NOENOUGH,

		[ProtoEnum(Name = "ERR_GARDEN_NOTINGARDEN", Value = 562)]
		ERR_GARDEN_NOTINGARDEN,

		[ProtoEnum(Name = "ERR_GARDEN_FOODBOOK_ACTIVED", Value = 563)]
		ERR_GARDEN_FOODBOOK_ACTIVED,

		[ProtoEnum(Name = "ERR_ROLE_LOGOUT", Value = 564)]
		ERR_ROLE_LOGOUT,

		[ProtoEnum(Name = "ERR_TEAM_INV_LOGOUT", Value = 565)]
		ERR_TEAM_INV_LOGOUT,

		[ProtoEnum(Name = "ERR_SKYCITY_LV", Value = 566)]
		ERR_SKYCITY_LV,

		[ProtoEnum(Name = "ERR_RESWAR_TEAM", Value = 567)]
		ERR_RESWAR_TEAM,

		[ProtoEnum(Name = "ERR_RESWAR_ACTIVITY", Value = 568)]
		ERR_RESWAR_ACTIVITY,

		[ProtoEnum(Name = "ERR_RESWAR_GROUP", Value = 569)]
		ERR_RESWAR_GROUP,

		[ProtoEnum(Name = "ERR_RESWAR_STATE", Value = 570)]
		ERR_RESWAR_STATE,

		[ProtoEnum(Name = "ERR_RESWAR_CD", Value = 571)]
		ERR_RESWAR_CD,

		[ProtoEnum(Name = "ERR_BAG_FULL", Value = 572)]
		ERR_BAG_FULL,

		[ProtoEnum(Name = "ERR_BAG_FULL_TAKEOFF_EQUIP", Value = 573)]
		ERR_BAG_FULL_TAKEOFF_EQUIP,

		[ProtoEnum(Name = "ERR_BAG_FULL_TAKEOFF_FASHION", Value = 574)]
		ERR_BAG_FULL_TAKEOFF_FASHION,

		[ProtoEnum(Name = "ERR_BAG_FULL_TAKEOFF_EMBLEM", Value = 575)]
		ERR_BAG_FULL_TAKEOFF_EMBLEM,

		[ProtoEnum(Name = "ERR_BAG_FULL_TAKEOFF_JADE", Value = 576)]
		ERR_BAG_FULL_TAKEOFF_JADE,

		[ProtoEnum(Name = "ERR_BAG_FULL_GIVE_MAIL_REWARD", Value = 577)]
		ERR_BAG_FULL_GIVE_MAIL_REWARD,

		[ProtoEnum(Name = "ERR_AUCT_PRICE_CHANGE", Value = 578)]
		ERR_AUCT_PRICE_CHANGE,

		[ProtoEnum(Name = "ERR_GMF_UPBATTLE_REPEAT", Value = 579)]
		ERR_GMF_UPBATTLE_REPEAT,

		[ProtoEnum(Name = "ERR_PANDORA_LACKOF_FIRE", Value = 580)]
		ERR_PANDORA_LACKOF_FIRE,

		[ProtoEnum(Name = "ERR_AUCT_AUCTOVER", Value = 581)]
		ERR_AUCT_AUCTOVER,

		[ProtoEnum(Name = "ERR_GOLDCLICK_LIMIT", Value = 582)]
		ERR_GOLDCLICK_LIMIT,

		[ProtoEnum(Name = "ERR_DRAGONCOIN_LIMIT", Value = 583)]
		ERR_DRAGONCOIN_LIMIT,

		[ProtoEnum(Name = "ERR_NOTGUILD", Value = 584)]
		ERR_NOTGUILD,

		[ProtoEnum(Name = "ERR_SCENE_NOT_PET", Value = 585)]
		ERR_SCENE_NOT_PET,

		[ProtoEnum(Name = "ERR_GUILDBONUS_ALLGET", Value = 586)]
		ERR_GUILDBONUS_ALLGET,

		[ProtoEnum(Name = "ERR_GUILDBUFF_GUILD", Value = 587)]
		ERR_GUILDBUFF_GUILD,

		[ProtoEnum(Name = "ERR_GUILDBUFF_POS", Value = 588)]
		ERR_GUILDBUFF_POS,

		[ProtoEnum(Name = "ERR_GUILDBUFF_CD", Value = 589)]
		ERR_GUILDBUFF_CD,

		[ProtoEnum(Name = "ERR_GUILDBUFF_ITEM", Value = 590)]
		ERR_GUILDBUFF_ITEM,

		[ProtoEnum(Name = "ERR_RESWAR_LEADER", Value = 591)]
		ERR_RESWAR_LEADER,

		[ProtoEnum(Name = "ERR_RESWAR_LACKPLAYER", Value = 592)]
		ERR_RESWAR_LACKPLAYER,

		[ProtoEnum(Name = "ERR_TEAM_INV_IN_FAMILY", Value = 593)]
		ERR_TEAM_INV_IN_FAMILY,

		[ProtoEnum(Name = "ERR_TASK_NO_ASK_HELPNUM", Value = 594)]
		ERR_TASK_NO_ASK_HELPNUM,

		[ProtoEnum(Name = "ERR_TASK_CANNOT_HELP", Value = 595)]
		ERR_TASK_CANNOT_HELP,

		[ProtoEnum(Name = "ERR_TASK_ALREADY_FINISH", Value = 596)]
		ERR_TASK_ALREADY_FINISH,

		[ProtoEnum(Name = "ERR_TASK_ALREADY_ASKED", Value = 597)]
		ERR_TASK_ALREADY_ASKED,

		[ProtoEnum(Name = "ERR_GARDEN_NOEXIST_FOODID", Value = 598)]
		ERR_GARDEN_NOEXIST_FOODID,

		[ProtoEnum(Name = "ERR_GARDEN_FOOD_NOALLOW", Value = 599)]
		ERR_GARDEN_FOOD_NOALLOW,

		[ProtoEnum(Name = "ERR_TASK_NO_ASKINFO", Value = 600)]
		ERR_TASK_NO_ASKINFO,

		[ProtoEnum(Name = "ERR_TASK_ASKITEM_REFRESH", Value = 601)]
		ERR_TASK_ASKITEM_REFRESH,

		[ProtoEnum(Name = "ERR_ANTI_CHEAT_DETECTED", Value = 305)]
		ERR_ANTI_CHEAT_DETECTED = 305,

		[ProtoEnum(Name = "ERR_MS_UNREADY", Value = 306)]
		ERR_MS_UNREADY,

		[ProtoEnum(Name = "ERR_PET_EXP_EQUAL", Value = 602)]
		ERR_PET_EXP_EQUAL = 602,

		[ProtoEnum(Name = "ERR_TASK_CANNT_HELPSELF", Value = 603)]
		ERR_TASK_CANNT_HELPSELF,

		[ProtoEnum(Name = "CanNotDelInGuildArena", Value = 604)]
		CanNotDelInGuildArena,

		[ProtoEnum(Name = "ERR_RESWAR_TEAMFIGHTING", Value = 605)]
		ERR_RESWAR_TEAMFIGHTING,

		[ProtoEnum(Name = "ERR_TASK_CANNOT_GIVEUP", Value = 606)]
		ERR_TASK_CANNOT_GIVEUP,

		[ProtoEnum(Name = "ERR_GUILD_INHERIT_NOT_EXIT", Value = 607)]
		ERR_GUILD_INHERIT_NOT_EXIT,

		[ProtoEnum(Name = "ERR_GUILD_INHERIT_GAP", Value = 608)]
		ERR_GUILD_INHERIT_GAP,

		[ProtoEnum(Name = "ERR_GUILD_INHERIT_LVL", Value = 609)]
		ERR_GUILD_INHERIT_LVL,

		[ProtoEnum(Name = "ERR_GUILD_INHERIT_TIMES", Value = 610)]
		ERR_GUILD_INHERIT_TIMES,

		[ProtoEnum(Name = "ERR_GUILD_INHERIT_MAP_WRONG", Value = 611)]
		ERR_GUILD_INHERIT_MAP_WRONG,

		[ProtoEnum(Name = "ERR_TEAMCOST_DIAMOND", Value = 612)]
		ERR_TEAMCOST_DIAMOND,

		[ProtoEnum(Name = "ERR_TEAMCOST_DRAGON", Value = 613)]
		ERR_TEAMCOST_DRAGON,

		[ProtoEnum(Name = "ERR_TEAM_PPTLIMIT", Value = 614)]
		ERR_TEAM_PPTLIMIT,

		[ProtoEnum(Name = "ERR_GUILD_INHERIT_CD_TIME", Value = 615)]
		ERR_GUILD_INHERIT_CD_TIME,

		[ProtoEnum(Name = "ERR_MS_UNNORMAL", Value = 616)]
		ERR_MS_UNNORMAL,

		[ProtoEnum(Name = "ERR_TEAMCOST_NUMLIMIT", Value = 617)]
		ERR_TEAMCOST_NUMLIMIT,

		[ProtoEnum(Name = "ERR_STATE_CANTCHANGE", Value = 618)]
		ERR_STATE_CANTCHANGE,

		[ProtoEnum(Name = "ERR_TEAM_MEMCOUNT_OVER", Value = 619)]
		ERR_TEAM_MEMCOUNT_OVER,

		[ProtoEnum(Name = "ERR_GUILD_INHERIT_CAN_NOT", Value = 620)]
		ERR_GUILD_INHERIT_CAN_NOT,

		[ProtoEnum(Name = "ERR_SYS_NOTOPEN", Value = 621)]
		ERR_SYS_NOTOPEN,

		[ProtoEnum(Name = "ERR_NAME_ALLNUM", Value = 622)]
		ERR_NAME_ALLNUM,

		[ProtoEnum(Name = "ERR_NAME_TOO_LONG", Value = 623)]
		ERR_NAME_TOO_LONG,

		[ProtoEnum(Name = "ERR_NAME_TOO_SHORT", Value = 624)]
		ERR_NAME_TOO_SHORT,

		[ProtoEnum(Name = "ERR_GUILD_INHERIT_OTHER_TIMES", Value = 625)]
		ERR_GUILD_INHERIT_OTHER_TIMES,

		[ProtoEnum(Name = "ERR_NEED_FIRST_PROMOTE", Value = 626)]
		ERR_NEED_FIRST_PROMOTE,

		[ProtoEnum(Name = "ERR_FM_NOANCHOR", Value = 627)]
		ERR_FM_NOANCHOR,

		[ProtoEnum(Name = "ERR_CAN_NOT_USE_PET_SKILL_BOOK", Value = 628)]
		ERR_CAN_NOT_USE_PET_SKILL_BOOK,

		[ProtoEnum(Name = "ERR_ENCHANT_MINLEVEL", Value = 629)]
		ERR_ENCHANT_MINLEVEL,

		[ProtoEnum(Name = "ERR_ENCHANT_LACKITEM", Value = 631)]
		ERR_ENCHANT_LACKITEM = 631,

		[ProtoEnum(Name = "ERR_ENCHANT_WRONGPOS", Value = 632)]
		ERR_ENCHANT_WRONGPOS,

		[ProtoEnum(Name = "ERR_PARTNER_NUM_INVALID", Value = 650)]
		ERR_PARTNER_NUM_INVALID = 650,

		[ProtoEnum(Name = "ERR_PARTNER_FDEGREE_NOT_ENOUGH", Value = 651)]
		ERR_PARTNER_FDEGREE_NOT_ENOUGH,

		[ProtoEnum(Name = "ERR_PARTNER_NOT_IN_MAIN_HALL", Value = 652)]
		ERR_PARTNER_NOT_IN_MAIN_HALL,

		[ProtoEnum(Name = "ERR_PARTNER_NOT_ENOUGH_DRAGON", Value = 653)]
		ERR_PARTNER_NOT_ENOUGH_DRAGON,

		[ProtoEnum(Name = "ERR_PARTNER_CD_NOT_OK", Value = 654)]
		ERR_PARTNER_CD_NOT_OK,

		[ProtoEnum(Name = "ERR_HORSE_ACTIVITY", Value = 655)]
		ERR_HORSE_ACTIVITY,

		[ProtoEnum(Name = "ERR_TEAM_WEEK_NEST_EXP", Value = 656)]
		ERR_TEAM_WEEK_NEST_EXP,

		[ProtoEnum(Name = "ERR_PARTNER_CHEST_TAKED", Value = 657)]
		ERR_PARTNER_CHEST_TAKED,

		[ProtoEnum(Name = "ERR_PARTNER_NO_PARTNER", Value = 658)]
		ERR_PARTNER_NO_PARTNER,

		[ProtoEnum(Name = "ERR_PARTNER_LN_NOT_ENOUGH", Value = 659)]
		ERR_PARTNER_LN_NOT_ENOUGH,

		[ProtoEnum(Name = "ERR_PARTNER_ALREADY_HAS", Value = 660)]
		ERR_PARTNER_ALREADY_HAS,

		[ProtoEnum(Name = "ERR_PARTNER_ALREADY_APPLY_LEAVE", Value = 661)]
		ERR_PARTNER_ALREADY_APPLY_LEAVE,

		[ProtoEnum(Name = "ERR_PARTNER_NOT_APPLY_LEAVE", Value = 662)]
		ERR_PARTNER_NOT_APPLY_LEAVE,

		[ProtoEnum(Name = "ERR_INVFIGHT_ROLE_LOGOUT", Value = 663)]
		ERR_INVFIGHT_ROLE_LOGOUT,

		[ProtoEnum(Name = "ERR_INVFIGHT_ME_LEVEL", Value = 664)]
		ERR_INVFIGHT_ME_LEVEL,

		[ProtoEnum(Name = "ERR_INVFIGHT_ME_SCENE", Value = 665)]
		ERR_INVFIGHT_ME_SCENE,

		[ProtoEnum(Name = "ERR_INVFIGHT_OTHER_LEVEL", Value = 666)]
		ERR_INVFIGHT_OTHER_LEVEL,

		[ProtoEnum(Name = "ERR_INVFIGHT_OTHER_SCENE", Value = 667)]
		ERR_INVFIGHT_OTHER_SCENE,

		[ProtoEnum(Name = "ERR_INVFIGHT_INV_REPEAT", Value = 668)]
		ERR_INVFIGHT_INV_REPEAT,

		[ProtoEnum(Name = "ERR_INVFIGHT_INV_COUNT_MAX", Value = 669)]
		ERR_INVFIGHT_INV_COUNT_MAX,

		[ProtoEnum(Name = "ERR_INVFIGHT_INV_TIME_OVER", Value = 670)]
		ERR_INVFIGHT_INV_TIME_OVER,

		[ProtoEnum(Name = "ERR_INVFIGHT_INV_DELAY", Value = 671)]
		ERR_INVFIGHT_INV_DELAY,

		[ProtoEnum(Name = "ERR_DOODAD_FULL", Value = 672)]
		ERR_DOODAD_FULL,

		[ProtoEnum(Name = "ERR_INVFIGHT_INV_TO_COUNT_MAX", Value = 673)]
		ERR_INVFIGHT_INV_TO_COUNT_MAX,

		[ProtoEnum(Name = "ERR_PARTNER_ITEM_NOT_FOUND", Value = 674)]
		ERR_PARTNER_ITEM_NOT_FOUND,

		[ProtoEnum(Name = "ERR_PARTNER_OTHER_BUYING", Value = 675)]
		ERR_PARTNER_OTHER_BUYING,

		[ProtoEnum(Name = "ERR_PARTNER_SHOP_NO_COUNT", Value = 676)]
		ERR_PARTNER_SHOP_NO_COUNT,

		[ProtoEnum(Name = "ERR_FRIEND_IS_PARTNER", Value = 677)]
		ERR_FRIEND_IS_PARTNER,

		[ProtoEnum(Name = "ERR_PANDORA_LACKOF_HEART", Value = 678)]
		ERR_PANDORA_LACKOF_HEART,

		[ProtoEnum(Name = "ERR_SELF_HAS_ALLIANCE", Value = 679)]
		ERR_SELF_HAS_ALLIANCE,

		[ProtoEnum(Name = "ERR_OTHER_HAS_ALLIANCE", Value = 680)]
		ERR_OTHER_HAS_ALLIANCE,

		[ProtoEnum(Name = "ERR_AUDIOTXT", Value = 681)]
		ERR_AUDIOTXT,

		[ProtoEnum(Name = "ERR_MENTOR_ASKMAXTODAY", Value = 682)]
		ERR_MENTOR_ASKMAXTODAY,

		[ProtoEnum(Name = "ERR_MENTOR_REFRESHTOOFAST", Value = 683)]
		ERR_MENTOR_REFRESHTOOFAST,

		[ProtoEnum(Name = "ERR_MENTOR_OTHER_ONLINE", Value = 684)]
		ERR_MENTOR_OTHER_ONLINE,

		[ProtoEnum(Name = "ERR_PARTNER_LEVEL_NOT_ENOUGH", Value = 685)]
		ERR_PARTNER_LEVEL_NOT_ENOUGH,

		[ProtoEnum(Name = "ERR_GCASTLE_NOT_IN_ACT", Value = 686)]
		ERR_GCASTLE_NOT_IN_ACT,

		[ProtoEnum(Name = "ERR_GCASTLE_NOT_IN_FIGHT", Value = 687)]
		ERR_GCASTLE_NOT_IN_FIGHT,

		[ProtoEnum(Name = "ERR_GCASTLE_ROLE_FULL", Value = 688)]
		ERR_GCASTLE_ROLE_FULL,

		[ProtoEnum(Name = "ERR_CARDMATCH_SIGNUP_LIMIT", Value = 689)]
		ERR_CARDMATCH_SIGNUP_LIMIT,

		[ProtoEnum(Name = "ERR_GUILDAUCT_PUBLIC_TIME", Value = 690)]
		ERR_GUILDAUCT_PUBLIC_TIME,

		[ProtoEnum(Name = "ERR_FASHIONCOMPOSE_TIMELIMIT", Value = 691)]
		ERR_FASHIONCOMPOSE_TIMELIMIT,

		[ProtoEnum(Name = "ERR_FASHIONCOMPOSE_QUALITY", Value = 692)]
		ERR_FASHIONCOMPOSE_QUALITY,

		[ProtoEnum(Name = "ERR_FASHIONCOMPOSE_FAILED", Value = 693)]
		ERR_FASHIONCOMPOSE_FAILED,

		[ProtoEnum(Name = "ERR_FASHIONCOMPOSE_POS", Value = 694)]
		ERR_FASHIONCOMPOSE_POS,

		[ProtoEnum(Name = "ERR_RESWAR_LEAVETEAM", Value = 695)]
		ERR_RESWAR_LEAVETEAM,

		[ProtoEnum(Name = "ERR_RECONNECT_FAIL", Value = 696)]
		ERR_RECONNECT_FAIL,

		[ProtoEnum(Name = "ERR_CANTCHOOSEHERO", Value = 697)]
		ERR_CANTCHOOSEHERO,

		[ProtoEnum(Name = "ERR_HERO_INVALID", Value = 698)]
		ERR_HERO_INVALID,

		[ProtoEnum(Name = "ERR_TEAM_SERVER_OPEN_TIME", Value = 699)]
		ERR_TEAM_SERVER_OPEN_TIME,

		[ProtoEnum(Name = "ERR_AUDIO_CHAT", Value = 700)]
		ERR_AUDIO_CHAT,

		[ProtoEnum(Name = "ERR_HERO_LACKMONEY", Value = 701)]
		ERR_HERO_LACKMONEY,

		[ProtoEnum(Name = "ERR_HEROBATTLE_CANTGETPRIZE", Value = 702)]
		ERR_HEROBATTLE_CANTGETPRIZE,

		[ProtoEnum(Name = "ERR_HEROBATTLE_ALREADYGET", Value = 703)]
		ERR_HEROBATTLE_ALREADYGET,

		[ProtoEnum(Name = "ERR_CAN_NOT_DEL_IN_GUILD_TERRITOYR", Value = 704)]
		ERR_CAN_NOT_DEL_IN_GUILD_TERRITOYR,

		[ProtoEnum(Name = "ERR_HORSE_TEAM", Value = 705)]
		ERR_HORSE_TEAM,

		[ProtoEnum(Name = "ERR_GCASTLE_ROLE_LEVEL", Value = 706)]
		ERR_GCASTLE_ROLE_LEVEL,

		[ProtoEnum(Name = "ERR_CAN_INGORE", Value = 707)]
		ERR_CAN_INGORE,

		[ProtoEnum(Name = "ERR_LEAGUE_NOT_IN_TEAM", Value = 708)]
		ERR_LEAGUE_NOT_IN_TEAM,

		[ProtoEnum(Name = "ERR_LEAGUE_ALREADY_HAS_TEAM", Value = 709)]
		ERR_LEAGUE_ALREADY_HAS_TEAM,

		[ProtoEnum(Name = "ERR_LEAGUE_TEAM_ROLE_NUM_INVALID", Value = 710)]
		ERR_LEAGUE_TEAM_ROLE_NUM_INVALID,

		[ProtoEnum(Name = "ERR_LEAGUE_HAS_NO_TEAM", Value = 711)]
		ERR_LEAGUE_HAS_NO_TEAM,

		[ProtoEnum(Name = "ERR_LEAGUE_TEAM_NOT_EXIST", Value = 712)]
		ERR_LEAGUE_TEAM_NOT_EXIST,

		[ProtoEnum(Name = "ERR_GARDEN_STEAL_LIMIT", Value = 713)]
		ERR_GARDEN_STEAL_LIMIT,

		[ProtoEnum(Name = "ERR_LEAGUE_TEAM_IN_MATCH", Value = 714)]
		ERR_LEAGUE_TEAM_IN_MATCH,

		[ProtoEnum(Name = "ERR_LEAGUE_TEAM_NOT_IN_MATCH", Value = 715)]
		ERR_LEAGUE_TEAM_NOT_IN_MATCH,

		[ProtoEnum(Name = "ERR_SKILL_NEED_EXPRESKILL", Value = 716)]
		ERR_SKILL_NEED_EXPRESKILL,

		[ProtoEnum(Name = "ERR_EQUIP_CANTFORGE", Value = 717)]
		ERR_EQUIP_CANTFORGE,

		[ProtoEnum(Name = "ERR_EQUIP_FORGE_LACK_ITEM", Value = 718)]
		ERR_EQUIP_FORGE_LACK_ITEM,

		[ProtoEnum(Name = "ERR_EQUIP_FORGE_LACK_STONE", Value = 719)]
		ERR_EQUIP_FORGE_LACK_STONE,

		[ProtoEnum(Name = "ERR_LEAGUE_ROLE_ALREADY_UP", Value = 720)]
		ERR_LEAGUE_ROLE_ALREADY_UP,

		[ProtoEnum(Name = "ERR_LEAGUE_ROLE_FIGHTING", Value = 721)]
		ERR_LEAGUE_ROLE_FIGHTING,

		[ProtoEnum(Name = "ERR_LEAGUE_ROLE_ALREADY_BATTLE", Value = 722)]
		ERR_LEAGUE_ROLE_ALREADY_BATTLE,

		[ProtoEnum(Name = "ERR_REQUEST_REPEAT", Value = 723)]
		ERR_REQUEST_REPEAT,

		[ProtoEnum(Name = "ERR_EQUIP_FORGE_FAILED", Value = 724)]
		ERR_EQUIP_FORGE_FAILED,

		[ProtoEnum(Name = "ERR_NOMAIL_GETREWARD", Value = 725)]
		ERR_NOMAIL_GETREWARD,

		[ProtoEnum(Name = "ERR_MIDAS_FAILED", Value = 726)]
		ERR_MIDAS_FAILED,

		[ProtoEnum(Name = "ERR_LEAGUE_TEAM_IN_BATTLE", Value = 727)]
		ERR_LEAGUE_TEAM_IN_BATTLE,

		[ProtoEnum(Name = "ERR_ENCHANT_NOTHAVE", Value = 728)]
		ERR_ENCHANT_NOTHAVE,

		[ProtoEnum(Name = "ERR_ENCHANT_ALREADYHAVE", Value = 729)]
		ERR_ENCHANT_ALREADYHAVE,

		[ProtoEnum(Name = "ERR_ENCHANT_TRANSFER_LEVEL_LIMIT", Value = 730)]
		ERR_ENCHANT_TRANSFER_LEVEL_LIMIT,

		[ProtoEnum(Name = "ERR_FM_NOINAUDIO", Value = 731)]
		ERR_FM_NOINAUDIO,

		[ProtoEnum(Name = "ERR_FM_NOINROOM", Value = 732)]
		ERR_FM_NOINROOM,

		[ProtoEnum(Name = "ERR_CHANGEPRO_LEVEL", Value = 733)]
		ERR_CHANGEPRO_LEVEL,

		[ProtoEnum(Name = "ERR_CHANGEPRO_TIME", Value = 734)]
		ERR_CHANGEPRO_TIME,

		[ProtoEnum(Name = "ERR_CHANGEPRO_COUNT", Value = 735)]
		ERR_CHANGEPRO_COUNT,

		[ProtoEnum(Name = "ERR_CHANGEPRO_INVALID", Value = 736)]
		ERR_CHANGEPRO_INVALID,

		[ProtoEnum(Name = "ERR_CHANGEPRO_SAMEPRO", Value = 737)]
		ERR_CHANGEPRO_SAMEPRO,

		[ProtoEnum(Name = "ERR_CHANGEPRO_ITEMLIMIT", Value = 738)]
		ERR_CHANGEPRO_ITEMLIMIT,

		[ProtoEnum(Name = "ERR_SMELT_MAXVALUE", Value = 739)]
		ERR_SMELT_MAXVALUE,

		[ProtoEnum(Name = "ERR_SPRITE_AWAKE_MAX", Value = 740)]
		ERR_SPRITE_AWAKE_MAX,

		[ProtoEnum(Name = "ERR_CHANGEPRO_KICK", Value = 741)]
		ERR_CHANGEPRO_KICK,

		[ProtoEnum(Name = "ERR_LEAGUE_NOT_IN_MATCH_TIME", Value = 742)]
		ERR_LEAGUE_NOT_IN_MATCH_TIME,

		[ProtoEnum(Name = "ERR_LEAGUE_TEAM_NOT_IN_BATTLE", Value = 743)]
		ERR_LEAGUE_TEAM_NOT_IN_BATTLE,

		[ProtoEnum(Name = "ERR_SPRITE_TRAIN_MAX", Value = 744)]
		ERR_SPRITE_TRAIN_MAX,

		[ProtoEnum(Name = "ERR_SPRITE_TRAIN_CHOOSEMAX", Value = 745)]
		ERR_SPRITE_TRAIN_CHOOSEMAX,

		[ProtoEnum(Name = "ERR_SPRITE_TRAIN_LACKITEM", Value = 746)]
		ERR_SPRITE_TRAIN_LACKITEM,

		[ProtoEnum(Name = "ERR_SPRITE_NOTTRAIN", Value = 747)]
		ERR_SPRITE_NOTTRAIN,

		[ProtoEnum(Name = "ERR_SPRITE_RESETTRAIN_LACKITEM", Value = 748)]
		ERR_SPRITE_RESETTRAIN_LACKITEM,

		[ProtoEnum(Name = "ERR_LEAGUE_ALREADY_FIGHTED", Value = 749)]
		ERR_LEAGUE_ALREADY_FIGHTED,

		[ProtoEnum(Name = "ERR_LEAGUE_NOT_IN_APPLY_TIME", Value = 750)]
		ERR_LEAGUE_NOT_IN_APPLY_TIME,

		[ProtoEnum(Name = "ERR_HORSE_INTEAM", Value = 751)]
		ERR_HORSE_INTEAM,

		[ProtoEnum(Name = "ERR_LEAGUE_INV_NOT_IN_TEAM", Value = 752)]
		ERR_LEAGUE_INV_NOT_IN_TEAM,

		[ProtoEnum(Name = "ERR_LEAGUE_INV_ALREADY_HAS_TEAM", Value = 753)]
		ERR_LEAGUE_INV_ALREADY_HAS_TEAM,

		[ProtoEnum(Name = "ERR_SPRITE_TRAIN_NOT_ENOUGH", Value = 754)]
		ERR_SPRITE_TRAIN_NOT_ENOUGH,

		[ProtoEnum(Name = "ERR_DECLAREWAR_OUT_TIME", Value = 756)]
		ERR_DECLAREWAR_OUT_TIME = 756,

		[ProtoEnum(Name = "ERR_LEAGUE_TEAM_CANNOT_CROSS", Value = 757)]
		ERR_LEAGUE_TEAM_CANNOT_CROSS,

		[ProtoEnum(Name = "ERR_DECLARATION_TOO_LONG", Value = 758)]
		ERR_DECLARATION_TOO_LONG,

		[ProtoEnum(Name = "ERR_CROSS_ZONE_UNUSABLE", Value = 759)]
		ERR_CROSS_ZONE_UNUSABLE,

		[ProtoEnum(Name = "ERR_NOT_DEL_GUILD_IN_TERR", Value = 760)]
		ERR_NOT_DEL_GUILD_IN_TERR,

		[ProtoEnum(Name = "ERR_GCASTLE_FIGHT_END", Value = 761)]
		ERR_GCASTLE_FIGHT_END,

		[ProtoEnum(Name = "ERR_CAREER_PVP_NOTOPEN", Value = 762)]
		ERR_CAREER_PVP_NOTOPEN,

		[ProtoEnum(Name = "ERR_APOLLO_CDN", Value = 763)]
		ERR_APOLLO_CDN,

		[ProtoEnum(Name = "ERR_LEAGUE_HAS_MEMBER_NOT_TEAM", Value = 764)]
		ERR_LEAGUE_HAS_MEMBER_NOT_TEAM,

		[ProtoEnum(Name = "ERR_POK_MATCH_ENDSOON", Value = 765)]
		ERR_POK_MATCH_ENDSOON,

		[ProtoEnum(Name = "ERR_QUESTCAREER_NOT_ONLINE", Value = 766)]
		ERR_QUESTCAREER_NOT_ONLINE,

		[ProtoEnum(Name = "ERR_MIDAS_BALANCE_NOTENOUTH", Value = 767)]
		ERR_MIDAS_BALANCE_NOTENOUTH,

		[ProtoEnum(Name = "ERR_HAS_JOIN_OTHER_GUILD_BOSS", Value = 768)]
		ERR_HAS_JOIN_OTHER_GUILD_BOSS,

		[ProtoEnum(Name = "ERR_AUTH_TOKEN_INVALID", Value = 769)]
		ERR_AUTH_TOKEN_INVALID,

		[ProtoEnum(Name = "ERR_TEAM_TICKET_LESS", Value = 770)]
		ERR_TEAM_TICKET_LESS,

		[ProtoEnum(Name = "ERR_TEAM_USE_TICKET_COUNT_LESS", Value = 771)]
		ERR_TEAM_USE_TICKET_COUNT_LESS,

		[ProtoEnum(Name = "ERR_TEAM_TICKET_CONFIG", Value = 772)]
		ERR_TEAM_TICKET_CONFIG,

		[ProtoEnum(Name = "ERR_TEAM_TICKET_SEAL", Value = 773)]
		ERR_TEAM_TICKET_SEAL,

		[ProtoEnum(Name = "ERR_INVALID_IBBUY", Value = 774)]
		ERR_INVALID_IBBUY,

		[ProtoEnum(Name = "ERR_CROSS_IBBUY", Value = 775)]
		ERR_CROSS_IBBUY,

		[ProtoEnum(Name = "ERR_GUILD_NAME_NULL", Value = 776)]
		ERR_GUILD_NAME_NULL,

		[ProtoEnum(Name = "ERR_GUILD_LOCK_NAME", Value = 777)]
		ERR_GUILD_LOCK_NAME,

		[ProtoEnum(Name = "ERR_ARGENTA_DAILY_GET", Value = 778)]
		ERR_ARGENTA_DAILY_GET,

		[ProtoEnum(Name = "ERR_WORLDBOSSGUILD_COUNTLIMIT", Value = 779)]
		ERR_WORLDBOSSGUILD_COUNTLIMIT,

		[ProtoEnum(Name = "ERR_WORLDBOSSGUILD_UNMATCH", Value = 780)]
		ERR_WORLDBOSSGUILD_UNMATCH,

		[ProtoEnum(Name = "ERR_HERO_EXPERIENCE_HAVE", Value = 781)]
		ERR_HERO_EXPERIENCE_HAVE,

		[ProtoEnum(Name = "ERR_PLATSHARE_FAILED", Value = 782)]
		ERR_PLATSHARE_FAILED,

		[ProtoEnum(Name = "ERR_HERO_ALREADY_CHOSEN", Value = 783)]
		ERR_HERO_ALREADY_CHOSEN,

		[ProtoEnum(Name = "ERR_SKY_NOT_TEAM_MEMBER", Value = 784)]
		ERR_SKY_NOT_TEAM_MEMBER,

		[ProtoEnum(Name = "ERR_SKY_ALREADY_HAS_TEAM", Value = 785)]
		ERR_SKY_ALREADY_HAS_TEAM,

		[ProtoEnum(Name = "ERR_SKY_HAS_NO_TEAM", Value = 786)]
		ERR_SKY_HAS_NO_TEAM,

		[ProtoEnum(Name = "ERR_SKY_INV_NOT_TEAM_MEMBER", Value = 787)]
		ERR_SKY_INV_NOT_TEAM_MEMBER,

		[ProtoEnum(Name = "ERR_SKY_TEAM_IN_MATCH", Value = 788)]
		ERR_SKY_TEAM_IN_MATCH,

		[ProtoEnum(Name = "ERR_SKY_INV_ALREADY_HAS_TEAM", Value = 789)]
		ERR_SKY_INV_ALREADY_HAS_TEAM,

		[ProtoEnum(Name = "ERR_SKY_TEAM_ROLE_NUM_INVALID", Value = 790)]
		ERR_SKY_TEAM_ROLE_NUM_INVALID,

		[ProtoEnum(Name = "ERR_SKY_TEAM_IN_BATTLE", Value = 791)]
		ERR_SKY_TEAM_IN_BATTLE,

		[ProtoEnum(Name = "ERR_SKY_HAS_NOT_TEAM_MEMBER", Value = 792)]
		ERR_SKY_HAS_NOT_TEAM_MEMBER,

		[ProtoEnum(Name = "ERR_MENTOR_COMPLETE_OTHER_OFFLINE_NEED_DAYS", Value = 793)]
		ERR_MENTOR_COMPLETE_OTHER_OFFLINE_NEED_DAYS,

		[ProtoEnum(Name = "ERR_MENTOR_COMPLETE_IN_RELATION_NEED_DAYS", Value = 794)]
		ERR_MENTOR_COMPLETE_IN_RELATION_NEED_DAYS,

		[ProtoEnum(Name = "ERR_TRANSFERR_OTHER_ROLES_LEAVE", Value = 795)]
		ERR_TRANSFERR_OTHER_ROLES_LEAVE,

		[ProtoEnum(Name = "ERR_PLAT_BANACC", Value = 796)]
		ERR_PLAT_BANACC,

		[ProtoEnum(Name = "ERR_RESWAR_DIFF_GUILD", Value = 797)]
		ERR_RESWAR_DIFF_GUILD,

		[ProtoEnum(Name = "ERR_SKY_ALREADY_FIGHTED", Value = 798)]
		ERR_SKY_ALREADY_FIGHTED,

		[ProtoEnum(Name = "ERR_SKY_TEAM_NO_DAILY_NUM", Value = 799)]
		ERR_SKY_TEAM_NO_DAILY_NUM,

		[ProtoEnum(Name = "ERR_IBGIFT_NOT_ENOUCH", Value = 800)]
		ERR_IBGIFT_NOT_ENOUCH,

		[ProtoEnum(Name = "ERR_IBGIFT_DAY_MAXBUYCOUNT", Value = 801)]
		ERR_IBGIFT_DAY_MAXBUYCOUNT,

		[ProtoEnum(Name = "ERR_IBGIFT_FRIEND", Value = 802)]
		ERR_IBGIFT_FRIEND,

		[ProtoEnum(Name = "ERR_ALREADY_BUYAILEEN", Value = 803)]
		ERR_ALREADY_BUYAILEEN,

		[ProtoEnum(Name = "ERR_GUILDACMPPATY_NOTOPEN", Value = 804)]
		ERR_GUILDACMPPATY_NOTOPEN,

		[ProtoEnum(Name = "ERR_GUILDACMPPATY_ERRSTAGE", Value = 805)]
		ERR_GUILDACMPPATY_ERRSTAGE,

		[ProtoEnum(Name = "ERR_GUILDACMPPATY_DISTANCE", Value = 806)]
		ERR_GUILDACMPPATY_DISTANCE,

		[ProtoEnum(Name = "ERR_MENTOR_ALREADY_INRELATION", Value = 807)]
		ERR_MENTOR_ALREADY_INRELATION,

		[ProtoEnum(Name = "ERR_GUILDACMPPATY_SPRITE_ONTEXIST", Value = 808)]
		ERR_GUILDACMPPATY_SPRITE_ONTEXIST,

		[ProtoEnum(Name = "ERR_BAG_FULL_CANT_COMPOSE", Value = 809)]
		ERR_BAG_FULL_CANT_COMPOSE,

		[ProtoEnum(Name = "ERR_BAG_FULL_TAKEOFF_ARTIFACT", Value = 810)]
		ERR_BAG_FULL_TAKEOFF_ARTIFACT,

		[ProtoEnum(Name = "ERR_GIFTIB_NOTGOODS", Value = 811)]
		ERR_GIFTIB_NOTGOODS,

		[ProtoEnum(Name = "ERR_ARTIFACT_COMPOSE_LEVELNOTEQUAL", Value = 812)]
		ERR_ARTIFACT_COMPOSE_LEVELNOTEQUAL,

		[ProtoEnum(Name = "ERR_ARTIFACT_COMPOSE_QUALITYNOTEQUAL", Value = 813)]
		ERR_ARTIFACT_COMPOSE_QUALITYNOTEQUAL,

		[ProtoEnum(Name = "ERR_ARTIFACT_COMPOSE_NUMBER", Value = 814)]
		ERR_ARTIFACT_COMPOSE_NUMBER,

		[ProtoEnum(Name = "ERR_ARTIFACT_COMPOSE_CANTCOMPOSE", Value = 815)]
		ERR_ARTIFACT_COMPOSE_CANTCOMPOSE,

		[ProtoEnum(Name = "ERR_CUSTOMBATTLE_INVALIDREQUEST", Value = 816)]
		ERR_CUSTOMBATTLE_INVALIDREQUEST,

		[ProtoEnum(Name = "ERR_CUSTOMBATTLE_WORLDNOTOPEN", Value = 817)]
		ERR_CUSTOMBATTLE_WORLDNOTOPEN,

		[ProtoEnum(Name = "ERR_CUSTOMBATTLE_HASJOIN", Value = 818)]
		ERR_CUSTOMBATTLE_HASJOIN,

		[ProtoEnum(Name = "ERR_CUSTOMBATTLE_NOTJOIN", Value = 819)]
		ERR_CUSTOMBATTLE_NOTJOIN,

		[ProtoEnum(Name = "ERR_CUSTOMBATTLE_CREATFAILED", Value = 820)]
		ERR_CUSTOMBATTLE_CREATFAILED,

		[ProtoEnum(Name = "ERR_CUSTOMBATTLE_LEVELLIMIT", Value = 821)]
		ERR_CUSTOMBATTLE_LEVELLIMIT,

		[ProtoEnum(Name = "ERR_CUSTOMBATTLE_ROELNOTEXIST", Value = 822)]
		ERR_CUSTOMBATTLE_ROELNOTEXIST,

		[ProtoEnum(Name = "ERR_CUSTOMBATTLE_CREATECONFINVALID", Value = 823)]
		ERR_CUSTOMBATTLE_CREATECONFINVALID,

		[ProtoEnum(Name = "ERR_CUSTOMBATTLE_JOINNOTRELATED", Value = 824)]
		ERR_CUSTOMBATTLE_JOINNOTRELATED,

		[ProtoEnum(Name = "ERR_CUSTOMBATTLE_JOINNOTINREADYTIME", Value = 825)]
		ERR_CUSTOMBATTLE_JOINNOTINREADYTIME,

		[ProtoEnum(Name = "ERR_CUSTOMBATTLE_JOINFULL", Value = 826)]
		ERR_CUSTOMBATTLE_JOINFULL,

		[ProtoEnum(Name = "ERR_CUSTOMBATTLE_JOININVALIDPASSWORD", Value = 827)]
		ERR_CUSTOMBATTLE_JOININVALIDPASSWORD,

		[ProtoEnum(Name = "ERR_CUSTOMBATTLE_JOINFAILED", Value = 828)]
		ERR_CUSTOMBATTLE_JOINFAILED,

		[ProtoEnum(Name = "ERR_CUSTOMBATTLE_NOTCREATER", Value = 829)]
		ERR_CUSTOMBATTLE_NOTCREATER,

		[ProtoEnum(Name = "ERR_CUSTOMBATTLE_BATTLENOTFIND", Value = 830)]
		ERR_CUSTOMBATTLE_BATTLENOTFIND,

		[ProtoEnum(Name = "ERR_CUSTOMBATTLE_MATCHFAILED", Value = 831)]
		ERR_CUSTOMBATTLE_MATCHFAILED,

		[ProtoEnum(Name = "ERR_IBGIFT_MAX_COUNT", Value = 832)]
		ERR_IBGIFT_MAX_COUNT,

		[ProtoEnum(Name = "ERR_ENCHANT_NOTHAVEATTRID", Value = 833)]
		ERR_ENCHANT_NOTHAVEATTRID,

		[ProtoEnum(Name = "ERR_EXTRA_EMBLEM_SLOT_FULL", Value = 834)]
		ERR_EXTRA_EMBLEM_SLOT_FULL,

		[ProtoEnum(Name = "ERR_EXTRA_EMBLEM_SLOT_LEVEL", Value = 835)]
		ERR_EXTRA_EMBLEM_SLOT_LEVEL,

		[ProtoEnum(Name = "ERR_IBGIFT_OVERMAXUNRECV", Value = 836)]
		ERR_IBGIFT_OVERMAXUNRECV,

		[ProtoEnum(Name = "ERR_TEAM_CANNOT_FORNOW", Value = 837)]
		ERR_TEAM_CANNOT_FORNOW,

		[ProtoEnum(Name = "ERR_ALREADY_REPORTED", Value = 838)]
		ERR_ALREADY_REPORTED,

		[ProtoEnum(Name = "ERR_CUSTOMBATTLE_REWARDCD", Value = 839)]
		ERR_CUSTOMBATTLE_REWARDCD,

		[ProtoEnum(Name = "ERR_CUSTOMBATTLE_REWARDCANGET", Value = 840)]
		ERR_CUSTOMBATTLE_REWARDCANGET,

		[ProtoEnum(Name = "ERR_FASHION_ITEM_NOT_ENOUGH", Value = 841)]
		ERR_FASHION_ITEM_NOT_ENOUGH,

		[ProtoEnum(Name = "ERR_GUILDPARTY_TRADIING", Value = 842)]
		ERR_GUILDPARTY_TRADIING,

		[ProtoEnum(Name = "ERR_SPACTIVITY_NOTOPEN", Value = 843)]
		ERR_SPACTIVITY_NOTOPEN,

		[ProtoEnum(Name = "ERR_BAGEXPAND_LESSITEM", Value = 844)]
		ERR_BAGEXPAND_LESSITEM,

		[ProtoEnum(Name = "ERR_BAGEXPAND_MAXCOUNT", Value = 845)]
		ERR_BAGEXPAND_MAXCOUNT,

		[ProtoEnum(Name = "ERR_SHOP_WEEKCOUNTLIMIT", Value = 846)]
		ERR_SHOP_WEEKCOUNTLIMIT,

		[ProtoEnum(Name = "ERR_GUILDBONUS_MAXNUM", Value = 847)]
		ERR_GUILDBONUS_MAXNUM,

		[ProtoEnum(Name = "ERR_SELF_GIFT_SELF", Value = 848)]
		ERR_SELF_GIFT_SELF,

		[ProtoEnum(Name = "ERR_IBSHOP_BUSY", Value = 849)]
		ERR_IBSHOP_BUSY,

		[ProtoEnum(Name = "ERR_ABYSS_LEVEL", Value = 850)]
		ERR_ABYSS_LEVEL,

		[ProtoEnum(Name = "ERR_GUILDCAMP_SELF_NOTIN", Value = 851)]
		ERR_GUILDCAMP_SELF_NOTIN,

		[ProtoEnum(Name = "ERR_GUILDCAMP_OTHER_NOTIN", Value = 852)]
		ERR_GUILDCAMP_OTHER_NOTIN,

		[ProtoEnum(Name = "ERR_SMELTCOUNT_ZERO", Value = 853)]
		ERR_SMELTCOUNT_ZERO,

		[ProtoEnum(Name = "ERR_CUSTOMBATTLE_REWARDHASGET", Value = 854)]
		ERR_CUSTOMBATTLE_REWARDHASGET,

		[ProtoEnum(Name = "ERR_CUSTOMBATTLE_PASSWORDINVALID", Value = 855)]
		ERR_CUSTOMBATTLE_PASSWORDINVALID,

		[ProtoEnum(Name = "ERR_CUSTOMBATTLE_CREATORLEAVE", Value = 856)]
		ERR_CUSTOMBATTLE_CREATORLEAVE,

		[ProtoEnum(Name = "ERR_GUILDCAMP_SPRITE_NOTEXIST", Value = 857)]
		ERR_GUILDCAMP_SPRITE_NOTEXIST,

		[ProtoEnum(Name = "ERR_TEAM_INV_TIMEOUT", Value = 858)]
		ERR_TEAM_INV_TIMEOUT,

		[ProtoEnum(Name = "ERR_FORGE_NOREPLACE", Value = 859)]
		ERR_FORGE_NOREPLACE,

		[ProtoEnum(Name = "ERR_CUSTOMBATTLE_NAMEMAX", Value = 860)]
		ERR_CUSTOMBATTLE_NAMEMAX,

		[ProtoEnum(Name = "ERR_CUSTOMBATTLE_NAMEMIN", Value = 861)]
		ERR_CUSTOMBATTLE_NAMEMIN,

		[ProtoEnum(Name = "ERR_CUSTOMBATTLE_NAMEINVALID", Value = 862)]
		ERR_CUSTOMBATTLE_NAMEINVALID,

		[ProtoEnum(Name = "ERR_REPORT_FORBID", Value = 863)]
		ERR_REPORT_FORBID,

		[ProtoEnum(Name = "ERR_TEAM_COST_CANCEL", Value = 864)]
		ERR_TEAM_COST_CANCEL,

		[ProtoEnum(Name = "ERR_TEAM_COST_WIN", Value = 865)]
		ERR_TEAM_COST_WIN,

		[ProtoEnum(Name = "ERR_CUSTOM_NOTOPEN", Value = 866)]
		ERR_CUSTOM_NOTOPEN,

		[ProtoEnum(Name = "ERR_CUSTOM_GMLIMIT", Value = 867)]
		ERR_CUSTOM_GMLIMIT,

		[ProtoEnum(Name = "ERR_MILITARY_TRIGGER_CHECK", Value = 868)]
		ERR_MILITARY_TRIGGER_CHECK,

		[ProtoEnum(Name = "ERR_MENTOR_INHERIT_ING", Value = 869)]
		ERR_MENTOR_INHERIT_ING,

		[ProtoEnum(Name = "ERR_MOBA_UPGRADENUM_EMPTY", Value = 870)]
		ERR_MOBA_UPGRADENUM_EMPTY,

		[ProtoEnum(Name = "ERR_FASHION_ERROR_COLOR", Value = 871)]
		ERR_FASHION_ERROR_COLOR,

		[ProtoEnum(Name = "ERR_FASHION_COLOR_UNLOOK", Value = 872)]
		ERR_FASHION_COLOR_UNLOOK,

		[ProtoEnum(Name = "ERR_FASHION_NO_HAIR", Value = 873)]
		ERR_FASHION_NO_HAIR,

		[ProtoEnum(Name = "ERR_FASHION_COLOR_LOOK", Value = 874)]
		ERR_FASHION_COLOR_LOOK,

		[ProtoEnum(Name = "ERR_MOBA_SIGNAL_TOOFAST", Value = 875)]
		ERR_MOBA_SIGNAL_TOOFAST,

		[ProtoEnum(Name = "ERR_NOT_BESPEAK", Value = 876)]
		ERR_NOT_BESPEAK,

		[ProtoEnum(Name = "ERR_PAIRPET_OUTRANGE", Value = 877)]
		ERR_PAIRPET_OUTRANGE,

		[ProtoEnum(Name = "ERR_PAIRPET_INVITEINVALID", Value = 878)]
		ERR_PAIRPET_INVITEINVALID,

		[ProtoEnum(Name = "ERR_ROLE_IN_OTHER_SERVER", Value = 879)]
		ERR_ROLE_IN_OTHER_SERVER,

		[ProtoEnum(Name = "ERR_MOBA_CANTMATCH", Value = 880)]
		ERR_MOBA_CANTMATCH,

		[ProtoEnum(Name = "ERR_PAIRPET_INVITEREPEAT", Value = 881)]
		ERR_PAIRPET_INVITEREPEAT,

		[ProtoEnum(Name = "ERR_PAIRPET_SCENEINVALID", Value = 882)]
		ERR_PAIRPET_SCENEINVALID,

		[ProtoEnum(Name = "ERR_PAIRPET_SELF", Value = 883)]
		ERR_PAIRPET_SELF,

		[ProtoEnum(Name = "ERR_PAIRPET_OTHER", Value = 884)]
		ERR_PAIRPET_OTHER,

		[ProtoEnum(Name = "ERR_PAIRPET_OTHERNOTIN", Value = 885)]
		ERR_PAIRPET_OTHERNOTIN,

		[ProtoEnum(Name = "ERR_MENTOR_OTHER_APPLY_BREAK", Value = 886)]
		ERR_MENTOR_OTHER_APPLY_BREAK,

		[ProtoEnum(Name = "ERR_MENTOR_ALREADY_COMPLETE_MENTOR", Value = 887)]
		ERR_MENTOR_ALREADY_COMPLETE_MENTOR,

		[ProtoEnum(Name = "ERR_MENTOR_OTHER_ALREADY_APPLY_INHERIT", Value = 888)]
		ERR_MENTOR_OTHER_ALREADY_APPLY_INHERIT,

		[ProtoEnum(Name = "ERR_MENTOR_CUR_STATUS_CANNOT_BREAK", Value = 889)]
		ERR_MENTOR_CUR_STATUS_CANNOT_BREAK,

		[ProtoEnum(Name = "ERR_CUSTOM_SAMEMATCH", Value = 890)]
		ERR_CUSTOM_SAMEMATCH,

		[ProtoEnum(Name = "ERR_CUSTOM_NOMATCHING", Value = 891)]
		ERR_CUSTOM_NOMATCHING,

		[ProtoEnum(Name = "ERR_MENTOR_CUR_STATUS_CANNOT_APPLYSTUDENT", Value = 892)]
		ERR_MENTOR_CUR_STATUS_CANNOT_APPLYSTUDENT,

		[ProtoEnum(Name = "ERR_MENTOR_CUR_STATUS_CANNOT_APPLYMASTER", Value = 893)]
		ERR_MENTOR_CUR_STATUS_CANNOT_APPLYMASTER,

		[ProtoEnum(Name = "ERR_TEAM_DIAMOND_COST_LIMIT", Value = 894)]
		ERR_TEAM_DIAMOND_COST_LIMIT,

		[ProtoEnum(Name = "ERR_ACT_NOT_OPEN", Value = 895)]
		ERR_ACT_NOT_OPEN,

		[ProtoEnum(Name = "ERR_MOBA_MOBMAXLEVEL", Value = 896)]
		ERR_MOBA_MOBMAXLEVEL,

		[ProtoEnum(Name = "ERR_ACTIVITY", Value = 897)]
		ERR_ACTIVITY,

		[ProtoEnum(Name = "ERR_NOCONDITION", Value = 898)]
		ERR_NOCONDITION,

		[ProtoEnum(Name = "ERR_SERVER_UNNORMAL", Value = 899)]
		ERR_SERVER_UNNORMAL,

		[ProtoEnum(Name = "ERR_CUSTOMBATTLE_BOUNTYMODE_NOTOPEN", Value = 900)]
		ERR_CUSTOMBATTLE_BOUNTYMODE_NOTOPEN,

		[ProtoEnum(Name = "ERR_GROUPCHAT_FULLGROUP", Value = 901)]
		ERR_GROUPCHAT_FULLGROUP,

		[ProtoEnum(Name = "ERR_GROUPCHAT_ROLENOCOUNT", Value = 902)]
		ERR_GROUPCHAT_ROLENOCOUNT,

		[ProtoEnum(Name = "ERR_GROUPCHAT_LEADERNOCOUNT", Value = 903)]
		ERR_GROUPCHAT_LEADERNOCOUNT,

		[ProtoEnum(Name = "ERR_GROUPCHAT_GROUPFULLMEMBERS", Value = 904)]
		ERR_GROUPCHAT_GROUPFULLMEMBERS,

		[ProtoEnum(Name = "ERR_UNUSE1", Value = 905)]
		ERR_UNUSE1,

		[ProtoEnum(Name = "ERR_HAVE_GOT_AWARD", Value = 906)]
		ERR_HAVE_GOT_AWARD,

		[ProtoEnum(Name = "ERR_ANCIENTPOWER_LESSPOINT", Value = 907)]
		ERR_ANCIENTPOWER_LESSPOINT,

		[ProtoEnum(Name = "ERR_ANCIENTPOWER_DEAD", Value = 908)]
		ERR_ANCIENTPOWER_DEAD,

		[ProtoEnum(Name = "ERR_JADE_DRAGONNOTENOUGH", Value = 909)]
		ERR_JADE_DRAGONNOTENOUGH,

		[ProtoEnum(Name = "ERR_WEDDING_NOT_EXISTS", Value = 910)]
		ERR_WEDDING_NOT_EXISTS,

		[ProtoEnum(Name = "ERR_WEDDING_ALREADY_INVITE", Value = 911)]
		ERR_WEDDING_ALREADY_INVITE,

		[ProtoEnum(Name = "ERR_WEDDING_NOT_INVITE", Value = 912)]
		ERR_WEDDING_NOT_INVITE,

		[ProtoEnum(Name = "ERR_WEDDING_NOT_APPLY", Value = 913)]
		ERR_WEDDING_NOT_APPLY,

		[ProtoEnum(Name = "ERR_MARRIAGE_LEVEL_NOTENOUGH", Value = 914)]
		ERR_MARRIAGE_LEVEL_NOTENOUGH,

		[ProtoEnum(Name = "ERR_MARRIAGE_NEED_TWO_NOTMARRY", Value = 915)]
		ERR_MARRIAGE_NEED_TWO_NOTMARRY,

		[ProtoEnum(Name = "ERR_MARRIAGE_DISTANCE_TOOFAR", Value = 916)]
		ERR_MARRIAGE_DISTANCE_TOOFAR,

		[ProtoEnum(Name = "ERR_WEDDING_OPER_CD", Value = 917)]
		ERR_WEDDING_OPER_CD,

		[ProtoEnum(Name = "ERR_WEDDING_ALREADY_VOWS", Value = 918)]
		ERR_WEDDING_ALREADY_VOWS,

		[ProtoEnum(Name = "ERR_WEDDING_HP_NOT_ENOUGH", Value = 919)]
		ERR_WEDDING_HP_NOT_ENOUGH,

		[ProtoEnum(Name = "ERR_WEDDING_NOT_OWNER", Value = 920)]
		ERR_WEDDING_NOT_OWNER,

		[ProtoEnum(Name = "ERR_MARRIAGE_NOTINMARRIAGE", Value = 921)]
		ERR_MARRIAGE_NOTINMARRIAGE,

		[ProtoEnum(Name = "ERR_MARRIAGE_ALREADY_APPLYDIVORCE", Value = 922)]
		ERR_MARRIAGE_ALREADY_APPLYDIVORCE,

		[ProtoEnum(Name = "ERR_MARRIAGE_NOT_DIVORCESTATUS", Value = 923)]
		ERR_MARRIAGE_NOT_DIVORCESTATUS,

		[ProtoEnum(Name = "ERR_MARRIAGE_ONLY_APPLIER_CANCLEDIVORCE", Value = 924)]
		ERR_MARRIAGE_ONLY_APPLIER_CANCLEDIVORCE,

		[ProtoEnum(Name = "ERR_FRIEND_DEGREE_NOTENOUGH", Value = 925)]
		ERR_FRIEND_DEGREE_NOTENOUGH,

		[ProtoEnum(Name = "ERR_WEDDING_ALREADY_HOLDED", Value = 926)]
		ERR_WEDDING_ALREADY_HOLDED,

		[ProtoEnum(Name = "ERR_WEDDING_ALREADY_TAKECAR", Value = 927)]
		ERR_WEDDING_ALREADY_TAKECAR,

		[ProtoEnum(Name = "ERR_INVALID_PAYROLE", Value = 928)]
		ERR_INVALID_PAYROLE,

		[ProtoEnum(Name = "ERR_WEDDING_IS_HOLDING", Value = 929)]
		ERR_WEDDING_IS_HOLDING,

		[ProtoEnum(Name = "ERR_WEDDING_NOT_RUNNING", Value = 930)]
		ERR_WEDDING_NOT_RUNNING,

		[ProtoEnum(Name = "ERR_LIVENESS_NOT_ENOUGH", Value = 931)]
		ERR_LIVENESS_NOT_ENOUGH,

		[ProtoEnum(Name = "ERR_CHEST_TAKED", Value = 932)]
		ERR_CHEST_TAKED,

		[ProtoEnum(Name = "ERR_WEDDING_ALREADY_APPLY", Value = 933)]
		ERR_WEDDING_ALREADY_APPLY,

		[ProtoEnum(Name = "ERR_GROUPCHAT_FULLGROUP_OTHER", Value = 934)]
		ERR_GROUPCHAT_FULLGROUP_OTHER,

		[ProtoEnum(Name = "ERR_GROUPCHAT_TIMEOUT", Value = 935)]
		ERR_GROUPCHAT_TIMEOUT,

		[ProtoEnum(Name = "ERR_GROUPCHAT_NO_MANAGER", Value = 936)]
		ERR_GROUPCHAT_NO_MANAGER,

		[ProtoEnum(Name = "ERR_ITEM_NOT_ENOUGH_COMMON", Value = 937)]
		ERR_ITEM_NOT_ENOUGH_COMMON,

		[ProtoEnum(Name = "ERR_WEDDINGCAR_CANT_IN_PET", Value = 938)]
		ERR_WEDDINGCAR_CANT_IN_PET,

		[ProtoEnum(Name = "ERR_WEDDINGCAR_OTHER_RUNNING", Value = 939)]
		ERR_WEDDINGCAR_OTHER_RUNNING,

		[ProtoEnum(Name = "ERR_ARTIFACT_CANTRECAST", Value = 940)]
		ERR_ARTIFACT_CANTRECAST,

		[ProtoEnum(Name = "ERR_ARTIFACT_CANTFUSE", Value = 941)]
		ERR_ARTIFACT_CANTFUSE,

		[ProtoEnum(Name = "ERR_ARTIFACT_FUSEFAILED", Value = 942)]
		ERR_ARTIFACT_FUSEFAILED,

		[ProtoEnum(Name = "ERR_ARTIFACT_FUSE_CONDITION", Value = 943)]
		ERR_ARTIFACT_FUSE_CONDITION,

		[ProtoEnum(Name = "ERR_ARTIFACT_CANTINSCRIPTION", Value = 944)]
		ERR_ARTIFACT_CANTINSCRIPTION,

		[ProtoEnum(Name = "ERR_WEDDING_ALREADY_REFUSE", Value = 945)]
		ERR_WEDDING_ALREADY_REFUSE,

		[ProtoEnum(Name = "ERR_WEDDING_NEED_TWO_MARRIAGE", Value = 946)]
		ERR_WEDDING_NEED_TWO_MARRIAGE,

		[ProtoEnum(Name = "ERR_SPRITE_NOTREBIRTH", Value = 947)]
		ERR_SPRITE_NOTREBIRTH,

		[ProtoEnum(Name = "ERR_TEAM_FASTMATCH_BUFF", Value = 948)]
		ERR_TEAM_FASTMATCH_BUFF,

		[ProtoEnum(Name = "ERR_TEAM_SERVER_NOT_MATCH", Value = 949)]
		ERR_TEAM_SERVER_NOT_MATCH,

		[ProtoEnum(Name = "ERR_DAILY_WEDDY_CANDY_OVERMAX", Value = 950)]
		ERR_DAILY_WEDDY_CANDY_OVERMAX,

		[ProtoEnum(Name = "ERR_MARRIAGE_NEED_TEAM", Value = 951)]
		ERR_MARRIAGE_NEED_TEAM,

		[ProtoEnum(Name = "ERR_BACKFLOW_BUYEND", Value = 952)]
		ERR_BACKFLOW_BUYEND,

		[ProtoEnum(Name = "ERR_NEED_MARRIAGE_TEAM", Value = 953)]
		ERR_NEED_MARRIAGE_TEAM,

		[ProtoEnum(Name = "ERR_DOENTERSCENE_FAILED", Value = 954)]
		ERR_DOENTERSCENE_FAILED,

		[ProtoEnum(Name = "ERR_WEDDING_INVITE_OVERMAX", Value = 955)]
		ERR_WEDDING_INVITE_OVERMAX,

		[ProtoEnum(Name = "ERR_ARTIFACT_INSCRIPTION_LEVEL", Value = 956)]
		ERR_ARTIFACT_INSCRIPTION_LEVEL,

		[ProtoEnum(Name = "ERR_TRANS_PASSIVE", Value = 957)]
		ERR_TRANS_PASSIVE,

		[ProtoEnum(Name = "ERR_TRANS_NONE", Value = 958)]
		ERR_TRANS_NONE,

		[ProtoEnum(Name = "ERR_TRANS_OTHERNOTEXIST", Value = 959)]
		ERR_TRANS_OTHERNOTEXIST,

		[ProtoEnum(Name = "ERR_TRANS_ITEMNOTENOUGH", Value = 960)]
		ERR_TRANS_ITEMNOTENOUGH,

		[ProtoEnum(Name = "ERR_TRANS_STATE_FAILED", Value = 961)]
		ERR_TRANS_STATE_FAILED,

		[ProtoEnum(Name = "ERR_TRANS_SCENE_INVALID", Value = 962)]
		ERR_TRANS_SCENE_INVALID,

		[ProtoEnum(Name = "ERR_GARDEN_EXPELSPRITE_MAX", Value = 963)]
		ERR_GARDEN_EXPELSPRITE_MAX,

		[ProtoEnum(Name = "ERR_OP_ROLE_LEAVE", Value = 964)]
		ERR_OP_ROLE_LEAVE,

		[ProtoEnum(Name = "ERR_BATTLEFIELD_NOT_OPEN", Value = 965)]
		ERR_BATTLEFIELD_NOT_OPEN,

		[ProtoEnum(Name = "ERR_BATTLEFIELD_LEVEL", Value = 966)]
		ERR_BATTLEFIELD_LEVEL,

		[ProtoEnum(Name = "ERR_TASK_NO_REFRESH_COUNT", Value = 967)]
		ERR_TASK_NO_REFRESH_COUNT,

		[ProtoEnum(Name = "ERR_CANT_FUSE", Value = 968)]
		ERR_CANT_FUSE,

		[ProtoEnum(Name = "ERR_FUSE_MAX", Value = 969)]
		ERR_FUSE_MAX,

		[ProtoEnum(Name = "ERR_TASK_NOT_TASK_ITEM", Value = 970)]
		ERR_TASK_NOT_TASK_ITEM,

		[ProtoEnum(Name = "ERR_COMPETEDRAGON_WRONG_DNID", Value = 971)]
		ERR_COMPETEDRAGON_WRONG_DNID,

		[ProtoEnum(Name = "ERR_CANNOT_PICK_THIS_ITEM", Value = 972)]
		ERR_CANNOT_PICK_THIS_ITEM,

		[ProtoEnum(Name = "ERR_NPCFL_NEED_REFRESH", Value = 973)]
		ERR_NPCFL_NEED_REFRESH,

		[ProtoEnum(Name = "ERR_NPCFL_NPC_LEVEL_MAX", Value = 974)]
		ERR_NPCFL_NPC_LEVEL_MAX,

		[ProtoEnum(Name = "ERR_NPCFL_ITEM_LESS", Value = 975)]
		ERR_NPCFL_ITEM_LESS,

		[ProtoEnum(Name = "ERR_NPCFL_EXP_LESS", Value = 976)]
		ERR_NPCFL_EXP_LESS,

		[ProtoEnum(Name = "ERR_NPCFL_UNITE_LEVEL_LESS", Value = 977)]
		ERR_NPCFL_UNITE_LEVEL_LESS,

		[ProtoEnum(Name = "ERR_NPCFL_GIVE_GIFT_COUNT_LESS", Value = 978)]
		ERR_NPCFL_GIVE_GIFT_COUNT_LESS,

		[ProtoEnum(Name = "ERR_NPCFL_BUY_GG_COUNT_LESS", Value = 979)]
		ERR_NPCFL_BUY_GG_COUNT_LESS,

		[ProtoEnum(Name = "ERR_NPCFL_DRAGON_COIN_LESS", Value = 980)]
		ERR_NPCFL_DRAGON_COIN_LESS,

		[ProtoEnum(Name = "ERR_DAILY_TASK_NO_REFRESH_COUNT", Value = 981)]
		ERR_DAILY_TASK_NO_REFRESH_COUNT,

		[ProtoEnum(Name = "ERR_DAILY_TASK_CANNT_REFRESH", Value = 982)]
		ERR_DAILY_TASK_CANNT_REFRESH,

		[ProtoEnum(Name = "ERR_DAILY_TASK_NO_BUY_COUNT", Value = 983)]
		ERR_DAILY_TASK_NO_BUY_COUNT,

		[ProtoEnum(Name = "ERR_DAILY_TASK_QUALITY_MAX", Value = 984)]
		ERR_DAILY_TASK_QUALITY_MAX,

		[ProtoEnum(Name = "ERR_DG_ALREADY_IN_DG", Value = 985)]
		ERR_DG_ALREADY_IN_DG,

		[ProtoEnum(Name = "ERR_DG_DGNAME_EXIST", Value = 986)]
		ERR_DG_DGNAME_EXIST,

		[ProtoEnum(Name = "ERR_DG_DGUILD_NOT_EXIST", Value = 987)]
		ERR_DG_DGUILD_NOT_EXIST,

		[ProtoEnum(Name = "ERR_DG_FULL", Value = 988)]
		ERR_DG_FULL,

		[ProtoEnum(Name = "ERR_DG_PPT_REQ", Value = 989)]
		ERR_DG_PPT_REQ,

		[ProtoEnum(Name = "ERR_DG_WAITAPPROVAL", Value = 990)]
		ERR_DG_WAITAPPROVAL,

		[ProtoEnum(Name = "ERR_DG_NOT_IN_GUILD", Value = 991)]
		ERR_DG_NOT_IN_GUILD,

		[ProtoEnum(Name = "ERR_DG_NO_PERMISSION", Value = 992)]
		ERR_DG_NO_PERMISSION,

		[ProtoEnum(Name = "ERR_DG_LOCK_NAME", Value = 993)]
		ERR_DG_LOCK_NAME,

		[ProtoEnum(Name = "ERR_DG_APPLY_FULL", Value = 994)]
		ERR_DG_APPLY_FULL,

		[ProtoEnum(Name = "ERR_DG_IN_CD", Value = 995)]
		ERR_DG_IN_CD,

		[ProtoEnum(Name = "ERR_DG_ITEM_NOT_FOUND", Value = 996)]
		ERR_DG_ITEM_NOT_FOUND,

		[ProtoEnum(Name = "ERR_DG_OTHER_BUYING", Value = 997)]
		ERR_DG_OTHER_BUYING,

		[ProtoEnum(Name = "ERR_DG_SHOP_NO_COUNT", Value = 998)]
		ERR_DG_SHOP_NO_COUNT,

		[ProtoEnum(Name = "ERR_DG_NOT_IN_SAME", Value = 999)]
		ERR_DG_NOT_IN_SAME,

		[ProtoEnum(Name = "ERR_DG_POSITION_FULL", Value = 1000)]
		ERR_DG_POSITION_FULL,

		[ProtoEnum(Name = "ERR_DAILY_TASK_OTHER_NO_HELPCOUNT", Value = 1001)]
		ERR_DAILY_TASK_OTHER_NO_HELPCOUNT,

		[ProtoEnum(Name = "ERR_UNOPEN_FUNCTION", Value = 1002)]
		ERR_UNOPEN_FUNCTION,

		[ProtoEnum(Name = "ERR_QUERYBOX_TIMELEFT", Value = 1003)]
		ERR_QUERYBOX_TIMELEFT,

		[ProtoEnum(Name = "ERR_GUILDPARTY_ENDING", Value = 1004)]
		ERR_GUILDPARTY_ENDING,

		[ProtoEnum(Name = "ERR_GUILDPARTY_HAVESUMMON", Value = 1005)]
		ERR_GUILDPARTY_HAVESUMMON,

		[ProtoEnum(Name = "ERR_KINGBACK_REWARD_COUNT_LIMIT", Value = 1006)]
		ERR_KINGBACK_REWARD_COUNT_LIMIT,

		[ProtoEnum(Name = "ERR_DG_NOT_IN_APPROVAL", Value = 1007)]
		ERR_DG_NOT_IN_APPROVAL,

		[ProtoEnum(Name = "ERR_GUILDPARTY_SUMMONING", Value = 1008)]
		ERR_GUILDPARTY_SUMMONING,

		[ProtoEnum(Name = "ERR_HG_FORBID", Value = 1009)]
		ERR_HG_FORBID,

		[ProtoEnum(Name = "ERR_FASHION_NOEXIST_EFFECTS", Value = 1010)]
		ERR_FASHION_NOEXIST_EFFECTS,

		[ProtoEnum(Name = "ERR_BACKFLOW_ALREADYGET", Value = 1011)]
		ERR_BACKFLOW_ALREADYGET,

		[ProtoEnum(Name = "ERR_BACKFLOW_LESSPOINT", Value = 1012)]
		ERR_BACKFLOW_LESSPOINT,

		[ProtoEnum(Name = "ERR_TEAM_CROSS_TEAM_CHANGE_EXP", Value = 1013)]
		ERR_TEAM_CROSS_TEAM_CHANGE_EXP,

		[ProtoEnum(Name = "ERR_TEAM_CHANGE_EXP_TO_CROSS", Value = 1014)]
		ERR_TEAM_CHANGE_EXP_TO_CROSS,

		[ProtoEnum(Name = "ERR_INVALID_STATE", Value = 1015)]
		ERR_INVALID_STATE,

		[ProtoEnum(Name = "ERR_CHANGE_SAMESCENE", Value = 1016)]
		ERR_CHANGE_SAMESCENE,

		[ProtoEnum(Name = "ERR_BACKFLOWSHOP_LESSFRESHCOUNT", Value = 1017)]
		ERR_BACKFLOWSHOP_LESSFRESHCOUNT,

		[ProtoEnum(Name = "ERR_BACKFLOWSHOP_NOTHAVEGOOD", Value = 1018)]
		ERR_BACKFLOWSHOP_NOTHAVEGOOD,

		[ProtoEnum(Name = "ERR_BACKFLOWSHOP_LACKDIAMOND", Value = 1019)]
		ERR_BACKFLOWSHOP_LACKDIAMOND,

		[ProtoEnum(Name = "ERR_BACKFLOWSHOP_LACKDRAGONCOIN", Value = 1020)]
		ERR_BACKFLOWSHOP_LACKDRAGONCOIN,

		[ProtoEnum(Name = "ERR_BACKFLOWSHOP_ALREADYBUY", Value = 1021)]
		ERR_BACKFLOWSHOP_ALREADYBUY,

		[ProtoEnum(Name = "ERR_BACKFLOWSHOP_SHOPCLOSE", Value = 1022)]
		ERR_BACKFLOWSHOP_SHOPCLOSE,

		[ProtoEnum(Name = "ERR_ALREADY_CHARGE_BACK", Value = 1023)]
		ERR_ALREADY_CHARGE_BACK,

		[ProtoEnum(Name = "ERR_FUSE_EXPMAX", Value = 1024)]
		ERR_FUSE_EXPMAX,

		[ProtoEnum(Name = "ERR_FUSE_BREAKLACKEXP", Value = 1025)]
		ERR_FUSE_BREAKLACKEXP,

		[ProtoEnum(Name = "ERR_KINGDOM_NOT_OPEN", Value = 1026)]
		ERR_KINGDOM_NOT_OPEN,

		[ProtoEnum(Name = "ERR_SWEEP_NOTPASS", Value = 1027)]
		ERR_SWEEP_NOTPASS,

		[ProtoEnum(Name = "ERR_SWEEP_DRAGONHARD_NOTPASS", Value = 1028)]
		ERR_SWEEP_DRAGONHARD_NOTPASS,

		[ProtoEnum(Name = "ERR_GCF_UP_PROFESSION_REPEAT", Value = 1029)]
		ERR_GCF_UP_PROFESSION_REPEAT,

		[ProtoEnum(Name = "ERR_INVALID_REQUEST_CROSS", Value = 1030)]
		ERR_INVALID_REQUEST_CROSS,

		[ProtoEnum(Name = "ERR_SWEEP_IN_TEAM", Value = 1031)]
		ERR_SWEEP_IN_TEAM,

		[ProtoEnum(Name = "ERR_CAMPDUEL_ALREADY_CHOSEN_CAMP", Value = 1032)]
		ERR_CAMPDUEL_ALREADY_CHOSEN_CAMP,

		[ProtoEnum(Name = "ERR_CAMPDUEL_NOCAMPID", Value = 1033)]
		ERR_CAMPDUEL_NOCAMPID,

		[ProtoEnum(Name = "ERR_CAMPDUEL_FREEINSPIRE_ZERO", Value = 1034)]
		ERR_CAMPDUEL_FREEINSPIRE_ZERO,

		[ProtoEnum(Name = "ERR_CAMPDUEL_MONEYINSPIRE_ZERO", Value = 1035)]
		ERR_CAMPDUEL_MONEYINSPIRE_ZERO,

		[ProtoEnum(Name = "ERR_CAMPDUEL_MONEYINSPIRE_LESSMONEY", Value = 1036)]
		ERR_CAMPDUEL_MONEYINSPIRE_LESSMONEY,

		[ProtoEnum(Name = "ERR_TEAM_DONOT_HANDLE", Value = 1037)]
		ERR_TEAM_DONOT_HANDLE,

		[ProtoEnum(Name = "ERR_GUILD_JZ_HALLPEM", Value = 1038)]
		ERR_GUILD_JZ_HALLPEM,

		[ProtoEnum(Name = "ERR_ARTIFACT_CANTREFINE", Value = 1039)]
		ERR_ARTIFACT_CANTREFINE,

		[ProtoEnum(Name = "ERR_TEAM_RIFT_CHANGE_LEADER", Value = 1040)]
		ERR_TEAM_RIFT_CHANGE_LEADER,

		[ProtoEnum(Name = "ERR_TEAM_RIFT_MATCH", Value = 1041)]
		ERR_TEAM_RIFT_MATCH,

		[ProtoEnum(Name = "ERR_TEAM_RIFT_CHANGE_EXP", Value = 1042)]
		ERR_TEAM_RIFT_CHANGE_EXP,

		[ProtoEnum(Name = "ERR_GUILD_JZ_LEVEL_NOTENOUGH", Value = 1043)]
		ERR_GUILD_JZ_LEVEL_NOTENOUGH,

		[ProtoEnum(Name = "ERR_GUILD_JZ_HALLPOINT_NOTENOUGH", Value = 1044)]
		ERR_GUILD_JZ_HALLPOINT_NOTENOUGH,

		[ProtoEnum(Name = "ERR_GUILD_JZ_SCHOOLPOINT_NOTENOUGH", Value = 1045)]
		ERR_GUILD_JZ_SCHOOLPOINT_NOTENOUGH,

		[ProtoEnum(Name = "ERR_GUILD_JZ_ROLE_FULLSCHOOL", Value = 1046)]
		ERR_GUILD_JZ_ROLE_FULLSCHOOL,

		[ProtoEnum(Name = "ERR_GUILD_JZ_ROLE_FULLHALL", Value = 1047)]
		ERR_GUILD_JZ_ROLE_FULLHALL,

		[ProtoEnum(Name = "ERR_GUILD_JZ_GUILD_FULLSCHOOL", Value = 1048)]
		ERR_GUILD_JZ_GUILD_FULLSCHOOL,

		[ProtoEnum(Name = "ERR_GUILD_JZ_GUILD_FULLHALL", Value = 1049)]
		ERR_GUILD_JZ_GUILD_FULLHALL,

		[ProtoEnum(Name = "ERR_RIFT_DIFFERENT_ID", Value = 1050)]
		ERR_RIFT_DIFFERENT_ID,

		[ProtoEnum(Name = "ERR_RIFT_FLOOR_NOT_ENOUGH", Value = 1051)]
		ERR_RIFT_FLOOR_NOT_ENOUGH,

		[ProtoEnum(Name = "ERR_AWAKE_NOTOPEN", Value = 1052)]
		ERR_AWAKE_NOTOPEN,

		[ProtoEnum(Name = "ERR_COUNT_NOT_ENOUGH", Value = 1053)]
		ERR_COUNT_NOT_ENOUGH,

		[ProtoEnum(Name = "ERR_PARTICIPATE_TIME_LIMIT", Value = 1054)]
		ERR_PARTICIPATE_TIME_LIMIT,

		[ProtoEnum(Name = "ERR_NEED_SECOND_PROMOTE", Value = 1055)]
		ERR_NEED_SECOND_PROMOTE,

		[ProtoEnum(Name = "ERR_TASK_NO_HELP_COUNT", Value = 1056)]
		ERR_TASK_NO_HELP_COUNT,

		[ProtoEnum(Name = "ERR_TEAM_RIFT_MAX_FLOOR", Value = 1057)]
		ERR_TEAM_RIFT_MAX_FLOOR,

		[ProtoEnum(Name = "ERR_TEAM_RIFT_WRONG_FLOOR", Value = 1058)]
		ERR_TEAM_RIFT_WRONG_FLOOR,

		[ProtoEnum(Name = "ERR_JZ_FULL_LEVEL", Value = 1059)]
		ERR_JZ_FULL_LEVEL,

		[ProtoEnum(Name = "ERR_TEAM_COSTITEM_LESS", Value = 1060)]
		ERR_TEAM_COSTITEM_LESS,

		[ProtoEnum(Name = "ERR_COMPETE_DRAGON_TICKET_NOTENGOUTH", Value = 1061)]
		ERR_COMPETE_DRAGON_TICKET_NOTENGOUTH,

		[ProtoEnum(Name = "ERR_SHADOWCAT_CANTGET", Value = 1062)]
		ERR_SHADOWCAT_CANTGET,

		[ProtoEnum(Name = "ERR_SHADOWCAT_ALREADYGET", Value = 1063)]
		ERR_SHADOWCAT_ALREADYGET
	}
}
