using System;

namespace XMainClient
{

	internal enum NoticeType
	{

		NT_SPRITE_SKILLCAST = 10070,

		NT_OPENSYS_BEGIN = 100001,

		NT_OPENSYS_GUILD_RED_PACKET = 100001,

		NT_OPENSYS_LIVE_PVP,

		NT_OPENSYS_LIVE_NEST,

		NT_OPENSYS_LIVE_PROTECTCAPTAIN,

		NT_OPENSYS_SPACTATE_LIVE_GUILDBATTLE,

		NT_OPENSYS_LIVE_DRAGON,

		NT_OPENSYS_CAREER_MAIN = 100100,

		NT_OPENSYS_CAREER_PVP,

		NT_OPENSYS_CAREER_Trophy,

		NT_OPENSYS_END = 101000,

		NT_INVITE_NORMALTEAM = 110001,

		NT_INVITE_GUILDTEAM,

		NT_INVITE_GUILD = 110011,

		NT_INVITE_GUILD_PRIVATE,

		NT_GUILD_Daily_DONATE_REQ = 200190,

		NT_GUILD_Weekly_DONATE_REQ = 210102,

		NT_GUILD_Weekly_Help_Thanks_REQ,

		NT_GUILD_Daily_Refresh_Thanks_REQ,

		NT_GROUPCHAT_RECRUIT_WORLD = 210016,

		NT_Wedding_INVITE_WORLD = 210020,

		NT_INVITE_DRAGON_GUILD = 110031
	}
}
